/**
 * Verdura Catalog v2 — Indian Market Research Addition
 * Sources: PlantOrbit, Ugaoo, NurseryLive, PlantsGuru
 *
 * Adds 16 plants, 13 seeds, 15 supplies
 */

import { PrismaClient, PlantCategory, PlantDifficulty, SeedCategory, SupplyCategory } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {

  // ─────────────────────────────────────────────────────────────────────────────
  // PLANTS
  // ─────────────────────────────────────────────────────────────────────────────
  const plants = [

    // ── SUCCULENTS ────────────────────────────────────────────────────────────
    {
      name: 'Echeveria Elegans',
      scientificName: 'Echeveria elegans',
      slug: 'echeveria-elegans',
      description: 'One of the most popular succulents in India — the "Mexican Snowball". Plump silvery-blue rosettes with pink-tipped leaves. Nearly indestructible, perfect for sunny windowsills and balconies. Produces pink bell-shaped flowers on arching stems in spring.',
      price: 149,
      comparePrice: 199,
      stock: 80,
      thumbnailUrl: 'https://images.unsplash.com/photo-1520302519878-88a7a5fbe8b9?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1520302519878-88a7a5fbe8b9?w=800&h=800&fit=crop'],
      categories: [PlantCategory.succulent, PlantCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['succulent', 'rosette', 'drought-tolerant', 'balcony', 'gifting'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Water only when soil is completely dry — every 10–14 days.',
      careSunlight: 'Bright direct sun 4–6 hours. South or west-facing window.',
      careHumidity: 'Low humidity preferred. Do not mist.',
      careTemperature: '15–35°C.',
      wateringIntervalDays: 12, fertiliserIntervalDays: 30,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Light', body: 'Needs 4–6 hours of direct sunlight. South or west-facing balcony is ideal. Without sufficient light it stretches (etiolates) and loses its compact rosette shape.' },
        { order: 2, icon: "💧", title: 'Watering', body: 'Soak-and-dry method: water thoroughly, drain fully, wait until soil is bone dry before watering again. In Indian summers every 7–10 days; in monsoon/winter every 14–21 days.' },
        { order: 3, icon: "🌱", title: 'Propagation', body: 'Twist a lower leaf cleanly off, let it callous 1 day, then place on dry cactus mix. Mist lightly every few days. Baby rosettes emerge in 3–4 weeks.' },
      ]}
    },

    {
      name: 'Haworthia Zebra Plant',
      scientificName: 'Haworthiopsis fasciata',
      slug: 'haworthia-zebra-plant',
      description: 'The perfect indoor succulent for low-light homes. White horizontal stripes on dark green leaves form a compact rosette. One of very few succulents that thrive in indirect light — ideal for desks, shelves, and north-facing windows. Near-indestructible.',
      price: 179,
      comparePrice: 249,
      stock: 100,
      thumbnailUrl: 'https://images.unsplash.com/photo-1535241749838-299277b6305f?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1535241749838-299277b6305f?w=800&h=800&fit=crop'],
      categories: [PlantCategory.succulent, PlantCategory.indoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['succulent', 'low-light', 'desk-plant', 'office', 'beginner-friendly'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Water every 2–3 weeks. Soil must be completely dry between waterings.',
      careSunlight: 'Bright indirect light. Avoid harsh afternoon sun.',
      careHumidity: 'Normal indoor humidity fine. No misting.',
      careTemperature: '15–32°C.',
      wateringIntervalDays: 18, fertiliserIntervalDays: 45,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Why Haworthia thrives indoors', body: 'Unlike most succulents, Haworthia evolved under shrubs — adapted to lower light. Thrives in bright indirect light, making it perfect for Indian flats and offices.' },
        { order: 2, icon: "💧", title: 'Watering', body: 'Water every 2–3 weeks in summer, once a month in winter. Soil must be bone dry before watering. Overwatering is the #1 killer.' },
        { order: 3, icon: "🌱", title: 'Pups', body: 'Produces offsets around the base. Separate once they have their own roots and pot individually.' },
      ]}
    },

    {
      name: 'String of Pearls',
      scientificName: 'Senecio rowleyanus',
      slug: 'string-of-pearls',
      description: 'Strings of perfect pea-shaped beads cascade over pot edges. Each bead stores water for exceptional drought tolerance. Perfect for hanging planters and high shelves. One of the most photographed succulents — endlessly popular on social media.',
      price: 199,
      comparePrice: 299,
      stock: 60,
      thumbnailUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&h=800&fit=crop'],
      categories: [PlantCategory.succulent, PlantCategory.indoor],
      difficulty: PlantDifficulty.intermediate,
      tags: ['succulent', 'trailing', 'hanging', 'drought-tolerant'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Every 2 weeks growing season, 3–4 weeks winter. Plump = good, shrivelled = thirsty, mushy = overwatered.',
      careSunlight: 'Bright indirect light with gentle morning sun.',
      careHumidity: 'Low to moderate. No misting.',
      careTemperature: '18–30°C.',
      wateringIntervalDays: 14, fertiliserIntervalDays: 30,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Reading the beads', body: 'Plump round beads = perfectly watered. Slightly shrivelled = needs water. Mushy translucent beads = overwatered (remove affected sections immediately).' },
        { order: 2, icon: "💧", title: 'Propagation', body: 'Lay a string on moist cactus soil, pin lightly, nodes root in 2 weeks. Or push cuttings directly into soil.' },
      ]}
    },

    {
      name: 'Jade Plant',
      scientificName: 'Crassula ovata',
      slug: 'jade-plant-crassula',
      description: 'The iconic "money tree" succulent. Thick oval leaves on woody stems give a bonsai-like appearance. Lives for decades. Deeply auspicious in Vastu and Feng Shui — believed to bring prosperity. Excellent gifting plant.',
      price: 199,
      comparePrice: 299,
      stock: 75,
      thumbnailUrl: 'https://images.unsplash.com/photo-1522547902298-51566e4fb383?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1522547902298-51566e4fb383?w=800&h=800&fit=crop'],
      categories: [PlantCategory.succulent, PlantCategory.indoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['succulent', 'vastu', 'feng-shui', 'gifting', 'long-lived'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Every 2 weeks. Allow soil to dry completely.',
      careSunlight: 'Bright indirect to direct morning light. 4–6 hours.',
      careHumidity: 'Tolerates dry indoor air.',
      careTemperature: '15–30°C.',
      wateringIntervalDays: 14, fertiliserIntervalDays: 30, repottingIntervalMonths: 24,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Vastu placement', body: 'Place at entrance or in the south-east corner (wealth corner) to attract prosperity. Avoid bedroom or bathroom.' },
        { order: 2, icon: "💧", title: 'Pruning', body: 'Prune in spring for compact bushy shape. Cuttings callous 2–3 days then plant in dry soil.' },
      ]}
    },

    {
      name: 'Aloe Vera',
      scientificName: 'Aloe barbadensis miller',
      slug: 'aloe-vera',
      description: 'The most useful plant you can own. Fleshy leaves filled with cooling gel that soothes burns, sunburn, and skin irritation. Thrives on neglect. Produces pups freely. A staple of every Indian household for skin care and home remedies.',
      price: 149,
      comparePrice: 199,
      stock: 120,
      thumbnailUrl: 'https://images.unsplash.com/photo-1596547609652-9cf5d8c10616?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1596547609652-9cf5d8c10616?w=800&h=800&fit=crop'],
      categories: [PlantCategory.succulent, PlantCategory.indoor, PlantCategory.herb],
      difficulty: PlantDifficulty.beginner,
      tags: ['medicinal', 'skin-care', 'drought-tolerant', 'beginner', 'kitchen', 'sunburn', 'first-aid'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Deeply every 2–3 weeks. Let soil dry completely. Never leave in standing water.',
      careSunlight: 'Bright indirect or direct morning sun.',
      careHumidity: 'Low humidity preferred.',
      careTemperature: '15–40°C.',
      wateringIntervalDays: 18, fertiliserIntervalDays: 60,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Using the gel', body: 'Snap off a lower leaf and slice lengthwise to extract clear inner gel. Apply to minor burns or sunburn. Do not consume raw aloe without medical advice.' },
        { order: 2, icon: "💧", title: 'Watering warning', body: 'Aloe is more often killed by overwatering than underwatering. Yellow, soft leaves = overwatered. Cut back and let soil dry completely.' },
      ]}
    },

    // ── TROPICALS ─────────────────────────────────────────────────────────────
    {
      name: 'Monstera Adansonii',
      scientificName: 'Monstera adansonii',
      slug: 'monstera-adansonii',
      description: 'The "Swiss Cheese Plant" — dramatic fenestrated leaves full of natural holes. Grows as a climber or trailer. Thrives in Indian humidity and indirect light. Each new leaf is larger and more fenestrated, making it a constantly evolving living sculpture.',
      price: 299,
      comparePrice: 449,
      stock: 50,
      thumbnailUrl: 'https://images.unsplash.com/photo-1598880940942-c8cd84e45451?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1598880940942-c8cd84e45451?w=800&h=800&fit=crop'],
      categories: [PlantCategory.tropical, PlantCategory.indoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['tropical', 'climbing', 'trailing', 'fenestrated', 'statement-plant'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'When top 2 inches of soil feel dry — every 7–10 days.',
      careSunlight: 'Bright indirect light.',
      careHumidity: '50–70%. Mist 2–3x per week.',
      careTemperature: '20–30°C.',
      wateringIntervalDays: 8, fertiliserIntervalDays: 21,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Why holes?', body: 'Fenestrations evolved to let wind and rain pass through in the wild forest canopy without tearing leaves.' },
        { order: 2, icon: "💧", title: 'Moss pole', body: 'Provide a moss or coir pole — leaves become larger and more fenestrated as the plant climbs.' },
      ]}
    },

    {
      name: 'Peace Lily',
      scientificName: 'Spathiphyllum wallisii',
      slug: 'peace-lily',
      description: 'NASA top-10 air purifier. Removes benzene, formaldehyde, and ammonia. Elegant white spathes against deep green glossy leaves. Thrives in low light. Droops dramatically when thirsty then revives fully after watering — the world\'s best watering reminder.',
      price: 249,
      comparePrice: 399,
      stock: 70,
      thumbnailUrl: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb6?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1593482892290-f54927ae1bb6?w=800&h=800&fit=crop'],
      categories: [PlantCategory.tropical, PlantCategory.indoor, PlantCategory.air_purifying],
      difficulty: PlantDifficulty.beginner,
      tags: ['air-purifying', 'low-light', 'nasa-approved', 'flowering', 'office', 'gifting'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'When leaves just begin to droop slightly. Every 5–7 days in summer.',
      careSunlight: 'Low to medium indirect light.',
      careHumidity: '40–60%. Mist weekly.',
      careTemperature: '18–30°C.',
      wateringIntervalDays: 6, fertiliserIntervalDays: 30,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'The droop trick', body: 'Peace Lily droops clearly when thirsty. Water promptly and it stands back up within hours. Do not wait until leaves are fully flat.' },
        { order: 2, icon: "💧", title: 'Air purification', body: 'NASA study found it removes acetone, ammonia, benzene, formaldehyde, trichloroethylene, and xylene.' },
      ]}
    },

    {
      name: 'Rubber Plant',
      scientificName: 'Ficus elastica',
      slug: 'rubber-plant-ficus',
      description: 'Bold architectural plant with large glossy leaves in deep burgundy or dark green. Grows into a statement indoor tree. Extremely durable — handles neglect, low humidity, and irregular watering. One of the best air purifiers and a classic of Indian interior decor.',
      price: 349,
      comparePrice: 499,
      stock: 55,
      thumbnailUrl: 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=800&h=800&fit=crop'],
      categories: [PlantCategory.tropical, PlantCategory.indoor, PlantCategory.air_purifying],
      difficulty: PlantDifficulty.beginner,
      tags: ['air-purifying', 'statement-plant', 'modern-decor', 'low-maintenance'],
      isBestseller: false, isNewArrival: false, isActive: true,
      careWatering: 'Every 7–10 days. Top 2 inches dry before watering.',
      careSunlight: 'Bright indirect light.',
      careHumidity: 'Normal indoor humidity. Wipe leaves monthly.',
      careTemperature: '15–30°C.',
      wateringIntervalDays: 8, fertiliserIntervalDays: 21, repottingIntervalMonths: 18,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Leaf care', body: 'Wipe large leaves with a damp cloth monthly to remove dust — this improves photosynthesis and keeps leaves glossy.' },
        { order: 2, icon: "💧", title: 'Pruning', body: 'Prune in spring. Cut above a node. Plant branches at cut point creating a bushier shape. Wear gloves — latex sap irritates skin.' },
      ]}
    },

    {
      name: 'ZZ Plant',
      scientificName: 'Zamioculcas zamiifolia',
      slug: 'zz-plant',
      description: 'The ultimate unkillable plant. Tolerates near-complete neglect — low light, drought, poor soil. Grows from underground rhizomes storing water for months. Glossy waxy leaves stay lush without care. Perfect for busy people, dark offices, and beginners.',
      price: 279,
      comparePrice: 399,
      stock: 65,
      thumbnailUrl: 'https://images.unsplash.com/photo-1620803366004-119b57f54cd6?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1620803366004-119b57f54cd6?w=800&h=800&fit=crop'],
      categories: [PlantCategory.tropical, PlantCategory.indoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['low-light', 'drought-tolerant', 'office', 'beginner', 'unkillable'],
      isBestseller: false, isNewArrival: true, isActive: true,
      careWatering: 'Every 3–4 weeks. Can survive 2 months without water.',
      careSunlight: 'Low to medium indirect light.',
      careHumidity: 'Tolerates very low humidity.',
      careTemperature: '15–35°C.',
      wateringIntervalDays: 25, fertiliserIntervalDays: 60,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Why it\'s unkillable', body: 'ZZ grows from large potato-like rhizomes that store massive water and nutrients, surviving months of drought. Even losing all stems, the rhizome often regenerates.' },
      ]}
    },

    {
      name: 'Areca Palm',
      scientificName: 'Dypsis lutescens',
      slug: 'areca-palm',
      description: 'India\'s most popular indoor palm — lush feathery arching fronds. One of the best natural humidifiers: a 1.8m plant releases ~1 litre of water vapour per day. Also a NASA top air purifier. Thrives in Indian climate.',
      price: 399,
      comparePrice: 599,
      stock: 40,
      thumbnailUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop'],
      categories: [PlantCategory.tropical, PlantCategory.indoor, PlantCategory.air_purifying],
      difficulty: PlantDifficulty.intermediate,
      tags: ['palm', 'air-purifying', 'humidifier', 'tropical', 'statement-plant', 'living-room'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Keep consistently moist. Every 5–7 days.',
      careSunlight: 'Bright indirect light.',
      careHumidity: '50–70%. Loves monsoon humidity.',
      careTemperature: '20–35°C.',
      wateringIntervalDays: 6, fertiliserIntervalDays: 21,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Natural humidifier', body: 'Areca transpires large amounts of moisture — perfect counter to dry AC air in Indian homes.' },
        { order: 2, icon: "💧", title: 'Yellow fronds', body: 'Some yellowing of lower fronds is normal. Many yellowing: check overwatering, underwatering, or light.' },
      ]}
    },

    // ── HERBS / MEDICINAL ─────────────────────────────────────────────────────
    {
      name: 'Tulsi (Holy Basil)',
      scientificName: 'Ocimum tenuiflorum',
      slug: 'tulsi-holy-basil',
      description: 'Sacred in every Hindu household — simultaneously a spiritual plant, air purifier, Ayurvedic medicine, and culinary herb. Releases oxygen 20 hours a day. Repels mosquitoes. Used in kadha, teas, and cooking. Simple to grow in any sunny spot.',
      price: 99,
      comparePrice: 149,
      stock: 150,
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Ocimum_tenuiflorum3.jpg/600px-Ocimum_tenuiflorum3.jpg',
      images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Ocimum_tenuiflorum3.jpg/800px-Ocimum_tenuiflorum3.jpg'],
      categories: [PlantCategory.herb, PlantCategory.indoor, PlantCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['sacred', 'ayurvedic', 'medicinal', 'herb', 'air-purifying', 'mosquito-repellent', 'edible', 'vastu'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Daily in summer, every 2 days otherwise. Likes consistently moist soil.',
      careSunlight: 'Full sun — minimum 6 hours direct.',
      careHumidity: 'Good airflow prevents fungal issues.',
      careTemperature: '20–40°C.',
      wateringIntervalDays: 1, fertiliserIntervalDays: 14,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Harvesting', body: 'Pick from the tips. Remove flower stalks promptly to keep producing fresh leaves. Never harvest more than 1/3 at once.' },
        { order: 2, icon: "💧", title: 'Kadha recipe', body: 'Boil 10–12 leaves in 2 cups water, add ginger, black pepper, honey. Traditional Ayurvedic immunity drink.' },
      ]}
    },

    {
      name: 'Curry Leaf Plant',
      scientificName: 'Murraya koenigii',
      slug: 'curry-leaf-plant',
      description: 'No Indian kitchen is complete without fresh curry leaves. Incomparably more fragrant than dried ones. Used in tadka, chutneys, and rice dishes. Grows vigorously once established. A culinary essential for every balcony kitchen garden.',
      price: 149,
      comparePrice: 199,
      stock: 80,
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Curry_leaf_plant.jpg/600px-Curry_leaf_plant.jpg',
      images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Curry_leaf_plant.jpg/800px-Curry_leaf_plant.jpg'],
      categories: [PlantCategory.herb, PlantCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['edible', 'culinary', 'herb', 'indian-cooking', 'medicinal', 'kitchen-garden'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Every 2–3 days. Allow top inch to dry.',
      careSunlight: 'Full sun — 6+ hours essential.',
      careHumidity: 'Tolerates all Indian humidity.',
      careTemperature: '18–40°C.',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Harvesting', body: 'Pick full sprigs rather than individual leaves — encourages branching. Regular harvesting keeps the plant bushy and productive.' },
        { order: 2, icon: "💧", title: 'Iron feeding', body: 'Apply iron-rich fertilizer once a month. Curry leaf plants love iron. Diluted buttermilk every 2 weeks is a traditional growth booster.' },
      ]}
    },

    // ── FLOWERING ─────────────────────────────────────────────────────────────
    {
      name: 'Adenium Desert Rose',
      scientificName: 'Adenium obesum',
      slug: 'adenium-desert-rose',
      description: 'Spectacular flowering plant with bonsai-like form and stunning trumpet flowers in pink, red, and white. Prized for its swollen caudex base and prolific blooms. Thrives in Indian heat. Nearly drought-proof once established. A showstopper on balconies and terraces.',
      price: 299,
      comparePrice: 449,
      stock: 40,
      thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Adenium_obesum.jpg/600px-Adenium_obesum.jpg',
      images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Adenium_obesum.jpg/800px-Adenium_obesum.jpg'],
      categories: [PlantCategory.flowering, PlantCategory.outdoor],
      difficulty: PlantDifficulty.intermediate,
      tags: ['flowering', 'drought-tolerant', 'bonsai-like', 'balcony', 'statement-plant', 'summer-bloomer'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Every 7–10 days growing season. Almost stop in winter.',
      careSunlight: 'Full direct sun 6+ hours. More sun = more flowers.',
      careHumidity: 'Low humidity preferred.',
      careTemperature: '25–40°C. Loves Indian heat.',
      wateringIntervalDays: 8, fertiliserIntervalDays: 14,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'The caudex', body: 'Repot raising the plant to expose the swollen base above soil — this is the most beautiful feature of a mature Adenium.' },
        { order: 2, icon: "💧", title: 'Bloom tips', body: 'Full sun + slightly small pot + phosphorus-rich fertilizer = maximum flowers. Stress the plant with reduced watering before growing season.' },
        { order: 3, icon: "🌱", title: 'Winter dormancy', body: 'May drop leaves in north Indian winters. Normal dormancy — stop watering. Resume when new leaves appear in spring.' },
      ]}
    },

    {
      name: 'Hibiscus (China Rose)',
      scientificName: 'Hibiscus rosa-sinensis',
      slug: 'hibiscus-china-rose',
      description: 'India\'s favourite flowering garden plant. Large flowers in red, pink, orange, yellow, and white bloom nearly year-round. Used in Ayurveda for hair care, as herbal tea for blood pressure, and as temple offerings. Fast growing and endlessly rewarding.',
      price: 199,
      comparePrice: 299,
      stock: 60,
      thumbnailUrl: 'https://images.unsplash.com/photo-1544928147-79a2dbc1f389?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1544928147-79a2dbc1f389?w=800&h=800&fit=crop'],
      categories: [PlantCategory.flowering, PlantCategory.outdoor, PlantCategory.herb],
      difficulty: PlantDifficulty.beginner,
      tags: ['flowering', 'medicinal', 'hair-care', 'herbal-tea', 'outdoor', 'year-round-bloomer'],
      isBestseller: true, isNewArrival: false, isActive: true,
      careWatering: 'Daily in summer. Every 2 days otherwise.',
      careSunlight: 'Full sun 6+ hours — essential for flowering.',
      careHumidity: 'Tolerates all Indian humidity. Thrives in monsoon.',
      careTemperature: '18–40°C.',
      wateringIntervalDays: 1, fertiliserIntervalDays: 14,
      careGuide: { create: [
        { order: 1, icon: "🌞", title: 'Hibiscus hair oil', body: 'Grind fresh flowers and leaves with coconut oil. Apply to scalp 1 hour before washing. Traditional Ayurvedic remedy for hair growth — backed by modern research.' },
        { order: 2, icon: "💧", title: 'Hibiscus tea', body: 'Steep 2–3 dried flowers in hot water for 5 min. Rich in Vitamin C. May help reduce blood pressure. Add honey to taste.' },
        { order: 3, icon: "🌱", title: 'More blooms', body: 'Prune by 1/3 after each blooming cycle. Feed potassium-rich fertilizer. Each branch tip produces a flower bud.' },
      ]}
    },
  ]

  console.log(`Adding ${plants.length} plants...`)
  for (const plant of plants) {
    const { careGuide, ...plantData } = plant
    const existing = await prisma.plant.findUnique({ where: { slug: plantData.slug } })
    if (existing) { console.log(`  SKIP: ${plantData.name}`); continue }
    await prisma.plant.create({ data: { ...plantData, isActive: true, careGuide } })
    console.log(`  ✓ ${plantData.name}`)
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // SEEDS
  // ─────────────────────────────────────────────────────────────────────────────
  const seeds = [
    {
      name: 'Marigold (African) Mixed Seeds',
      scientificName: 'Tagetes erecta',
      slug: 'marigold-african-mixed-seeds',
      description: 'Big pompom flowers in orange, yellow, and gold — India\'s quintessential garden flower. Used in garlands, puja, and festivals. Easy to grow. Blooms in 6–8 weeks. Natural pest repellent — plant near vegetables.',
      price: 59, stock: 200,
      thumbnailUrl: 'https://images.unsplash.com/photo-1531645928-b56c7394fc64?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1531645928-b56c7394fc64?w=800&h=800&fit=crop'],
      categories: [SeedCategory.flowering],
      difficulty: PlantDifficulty.beginner,
      tags: ['marigold', 'festival', 'puja', 'easy', 'pest-repellent'],
      isBestseller: true, isNewArrival: false, isActive: true,
      seedsPerPacket: 50,
      germinationDays: '5–7 days',
      sowingDepth: '0.5 cm',
      sowingMethod: 'Direct sow or seedling tray',
      sowingSeason: 'Year-round; best Oct–Feb and Jun–Aug',
      harvestDays: '45–60 days to first bloom',
    },
    {
      name: 'Sunflower Giant Seeds',
      scientificName: 'Helianthus annuus',
      slug: 'sunflower-giant-seeds',
      description: 'Grow giant sunflowers 1.5–2m tall with 25–30cm golden flower heads. Edible seeds attract birds. Grows rapidly and is nearly impossible to fail. Perfect for children.',
      price: 69, stock: 150,
      thumbnailUrl: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=800&h=800&fit=crop'],
      categories: [SeedCategory.flowering, SeedCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['sunflower', 'giant', 'edible-seeds', 'birds', 'easy', 'kids'],
      isBestseller: false, isNewArrival: false, isActive: true,
      seedsPerPacket: 15,
      germinationDays: '5–10 days',
      sowingDepth: '2 cm',
      sowingMethod: 'Direct sow',
      sowingSeason: 'Oct–Feb and Jul–Sep',
      harvestDays: '60–80 days to bloom',
    },
    {
      name: 'Zinnia Double Mix Seeds',
      scientificName: 'Zinnia elegans',
      slug: 'zinnia-double-mix-seeds',
      description: 'Vibrant double pom-pom flowers in every colour. Blooms continuously for months. Loved by butterflies. Excellent for cut flowers. One of the easiest and most rewarding flowers to grow.',
      price: 59, stock: 180,
      thumbnailUrl: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800&h=800&fit=crop'],
      categories: [SeedCategory.flowering],
      difficulty: PlantDifficulty.beginner,
      tags: ['zinnia', 'butterfly-garden', 'cut-flowers', 'easy', 'colourful'],
      isBestseller: true, isNewArrival: false, isActive: true,
      seedsPerPacket: 30,
      germinationDays: '5–7 days',
      sowingDepth: '0.5 cm',
      sowingMethod: 'Direct sow or seedling tray',
      sowingSeason: 'Aug–Nov',
      harvestDays: '50–60 days to bloom',
    },
    {
      name: 'Petunia Mix Seeds',
      scientificName: 'Petunia hybrida',
      slug: 'petunia-mix-seeds',
      description: 'Cascading trumpets of colour for hanging baskets and window boxes. Blooms winter through spring in India with intense evening fragrance. Most popular balcony flower in Indian cities.',
      price: 79, stock: 120,
      thumbnailUrl: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800&h=800&fit=crop'],
      categories: [SeedCategory.flowering],
      difficulty: PlantDifficulty.beginner,
      tags: ['petunia', 'fragrant', 'hanging-basket', 'winter-flower', 'balcony'],
      isBestseller: false, isNewArrival: false, isActive: true,
      seedsPerPacket: 30,
      germinationDays: '7–10 days',
      sowingDepth: '0.2 cm (surface sow)',
      sowingMethod: 'Seedling tray, do not cover seeds',
      sowingSeason: 'Sep–Nov sowing; blooms Nov–Mar',
      harvestDays: '70–80 days to bloom',
    },
    {
      name: 'Lavender French Seeds',
      scientificName: 'Lavandula dentata',
      slug: 'lavender-french-seeds',
      description: 'Grow your own lavender — purple spikes intensely fragrant above silver-grey foliage. Useful for aromatherapy, sleep pillows, cooking, and insect repellent. Grows in cooler Indian climates and during winter in plains.',
      price: 99, stock: 80,
      thumbnailUrl: 'https://images.unsplash.com/photo-1595407753234-0882f1e77954?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1595407753234-0882f1e77954?w=800&h=800&fit=crop'],
      categories: [SeedCategory.flowering, SeedCategory.herb],
      difficulty: PlantDifficulty.intermediate,
      tags: ['lavender', 'fragrant', 'aromatherapy', 'medicinal', 'insect-repellent'],
      isBestseller: false, isNewArrival: false, isActive: true,
      seedsPerPacket: 30,
      germinationDays: '14–21 days',
      sowingDepth: '0.3 cm',
      sowingMethod: 'Seedling tray; chill seeds 2 weeks in fridge before sowing',
      sowingSeason: 'Oct–Feb in plains; year-round in hills',
      harvestDays: '90–180 days to bloom',
    },
    {
      name: 'Cherry Tomato Seeds',
      scientificName: 'Solanum lycopersicum var. cerasiforme',
      slug: 'cherry-tomato-seeds',
      description: 'Sweet bite-sized tomatoes in a 12" balcony pot. Far more flavourful than store-bought. Produces prolifically for months — a single plant can yield hundreds of fruits. Perfect intro to growing your own food.',
      price: 99, stock: 150,
      thumbnailUrl: 'https://images.unsplash.com/photo-1592921870789-04563d55041c?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1592921870789-04563d55041c?w=800&h=800&fit=crop'],
      categories: [SeedCategory.vegetable],
      difficulty: PlantDifficulty.beginner,
      tags: ['tomato', 'cherry-tomato', 'balcony-garden', 'edible', 'easy', 'kids'],
      isBestseller: true, isNewArrival: false, isActive: true,
      seedsPerPacket: 30,
      germinationDays: '5–8 days',
      sowingDepth: '0.5 cm',
      sowingMethod: 'Seedling tray then transplant',
      sowingSeason: 'Aug–Oct; harvest Nov–Mar',
      harvestDays: '55–70 days after transplant',
    },
    {
      name: 'Chilli (Green) Desi Seeds',
      scientificName: 'Capsicum annuum',
      slug: 'chilli-green-desi-seeds',
      description: 'Grow fresh green chillies year-round in a pot. Desi varieties are sharper and more flavourful than commercial ones. Productive for 2–3 years in warm climates. One plant supplies daily cooking needs.',
      price: 59, stock: 180,
      thumbnailUrl: 'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=800&h=800&fit=crop'],
      categories: [SeedCategory.vegetable],
      difficulty: PlantDifficulty.beginner,
      tags: ['chilli', 'spice', 'container-growing', 'year-round', 'indian-cooking'],
      isBestseller: true, isNewArrival: false, isActive: true,
      seedsPerPacket: 30,
      germinationDays: '7–10 days',
      sowingDepth: '0.5 cm',
      sowingMethod: 'Seedling tray then transplant',
      sowingSeason: 'Year-round',
      harvestDays: '60–80 days after transplant',
    },
    {
      name: 'Spinach (Palak) Seeds',
      scientificName: 'Spinacia oleracea',
      slug: 'spinach-palak-seeds',
      description: 'Fast-growing and nutritious. Fresh homegrown spinach is tenderer and more flavourful than store-bought. Harvest outer leaves in 3–4 weeks. Perfect for balcony boxes or grow bags.',
      price: 49, stock: 200,
      thumbnailUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&h=800&fit=crop'],
      categories: [SeedCategory.vegetable],
      difficulty: PlantDifficulty.beginner,
      tags: ['spinach', 'palak', 'fast-growing', 'nutritious', 'winter-crop', 'balcony'],
      isBestseller: false, isNewArrival: false, isActive: true,
      seedsPerPacket: 100,
      germinationDays: '5–7 days',
      sowingDepth: '1 cm',
      sowingMethod: 'Direct sow',
      sowingSeason: 'Sep–Feb',
      harvestDays: '25–35 days (baby leaf)',
    },
    {
      name: 'Coriander (Dhaniya) Seeds',
      scientificName: 'Coriandrum sativum',
      slug: 'coriander-dhaniya-seeds',
      description: 'India\'s most used herb — fresh dhaniya added to nearly every dish. Grow a continuous supply at home by sowing every 3 weeks. Both leaves and seeds are used in cooking. Completes a leaf-harvest cycle in just 3–4 weeks.',
      price: 49, stock: 250,
      thumbnailUrl: 'https://images.unsplash.com/photo-1566140967404-b8b3932483f5?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1566140967404-b8b3932483f5?w=800&h=800&fit=crop'],
      categories: [SeedCategory.herb],
      difficulty: PlantDifficulty.beginner,
      tags: ['coriander', 'dhaniya', 'herb', 'indian-cooking', 'fast-growing', 'kitchen-garden'],
      isBestseller: true, isNewArrival: false, isActive: true,
      seedsPerPacket: 100,
      germinationDays: '7–10 days',
      sowingDepth: '1 cm',
      sowingMethod: 'Direct sow (crush seed lightly before sowing)',
      sowingSeason: 'Sep–Feb; can grow year-round in cool spots',
      harvestDays: '21–28 days (leaf harvest)',
    },
    {
      name: 'Mint (Pudina) Seeds',
      scientificName: 'Mentha spicata',
      slug: 'mint-pudina-seeds',
      description: 'Fresh mint for chutneys, raita, chai, and mojitos — always within reach. Best contained in a pot to prevent spreading. Also a digestive aid and mood-lifter.',
      price: 69, stock: 150,
      thumbnailUrl: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=800&h=800&fit=crop'],
      categories: [SeedCategory.herb],
      difficulty: PlantDifficulty.beginner,
      tags: ['mint', 'pudina', 'herb', 'culinary', 'chutney', 'raita', 'digestive'],
      isBestseller: false, isNewArrival: false, isActive: true,
      seedsPerPacket: 50,
      germinationDays: '10–14 days',
      sowingDepth: '0.2 cm (surface sow)',
      sowingMethod: 'Seedling tray; keep moist',
      sowingSeason: 'Year-round; best in cooler months',
      harvestDays: '30 days to first harvest',
    },
    {
      name: 'Italian Basil Seeds',
      scientificName: 'Ocimum basilicum',
      slug: 'italian-basil-seeds',
      description: 'Aromatic basil for pasta, pizza, pesto, and salads. Grows rapidly in Indian warmth. Repels aphids and mosquitoes. Pinch flower buds to keep producing leaves all season.',
      price: 79, stock: 130,
      thumbnailUrl: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=800&h=800&fit=crop'],
      categories: [SeedCategory.herb],
      difficulty: PlantDifficulty.beginner,
      tags: ['basil', 'herb', 'italian', 'cooking', 'pesto', 'pest-repellent', 'fragrant'],
      isBestseller: false, isNewArrival: false, isActive: true,
      seedsPerPacket: 100,
      germinationDays: '5–7 days',
      sowingDepth: '0.3 cm',
      sowingMethod: 'Direct sow or seedling tray',
      sowingSeason: 'Feb–Oct',
      harvestDays: '28–35 days to harvest',
    },
    {
      name: 'Fenugreek (Methi) Seeds for Growing',
      scientificName: 'Trigonella foenum-graecum',
      slug: 'fenugreek-methi-growing-seeds',
      description: 'Grow fresh methi leaves — softer and more aromatic than shop bundles. Baby leaves ready in just 2–3 weeks. Used in parathas, dal, curries. Ayurvedic powerhouse for blood sugar, hair growth, and digestion.',
      price: 39, stock: 200,
      thumbnailUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&h=800&fit=crop'],
      categories: [SeedCategory.herb, SeedCategory.vegetable],
      difficulty: PlantDifficulty.beginner,
      tags: ['methi', 'fenugreek', 'herb', 'indian-cooking', 'medicinal', 'ayurvedic', 'fast-growing'],
      isBestseller: true, isNewArrival: false, isActive: true,
      seedsPerPacket: 200,
      germinationDays: '3–5 days',
      sowingDepth: '1 cm',
      sowingMethod: 'Direct sow; soak seeds 8 hours before sowing',
      sowingSeason: 'Sep–Feb',
      harvestDays: '15–20 days (baby leaf)',
    },
    {
      name: 'Cosmos Mix Seeds',
      scientificName: 'Cosmos bipinnatus',
      slug: 'cosmos-mix-seeds-v2',
      description: 'Delicate feathery foliage with large daisy-like flowers in pink, white, and crimson. Extremely easy — throw seeds, water, and watch them bloom. Self-seeds prolifically. Attracts butterflies and bees. Perfect for filling garden beds quickly.',
      price: 49, stock: 160,
      thumbnailUrl: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800&h=800&fit=crop'],
      categories: [SeedCategory.flowering],
      difficulty: PlantDifficulty.beginner,
      tags: ['cosmos', 'butterfly-garden', 'easy', 'self-seeding', 'cut-flowers'],
      isBestseller: false, isNewArrival: false, isActive: true,
      seedsPerPacket: 40,
      germinationDays: '5–7 days',
      sowingDepth: '0.5 cm',
      sowingMethod: 'Direct sow',
      sowingSeason: 'Aug–Nov',
      harvestDays: '50–70 days to bloom',
    },
  ]

  console.log(`\nAdding ${seeds.length} seeds...`)
  for (const seed of seeds) {
    const existing = await prisma.seed.findUnique({ where: { slug: seed.slug } })
    if (existing) { console.log(`  SKIP: ${seed.name}`); continue }
    await prisma.seed.create({ data: { ...seed, isActive: true } })
    console.log(`  ✓ ${seed.name}`)
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // SUPPLIES
  // ─────────────────────────────────────────────────────────────────────────────
  const supplies = [
    // ── SOIL ──────────────────────────────────────────────────────────────────
    {
      name: 'Cocopeat Block 650g',
      slug: 'cocopeat-block-650g',
      description: 'Premium compressed cocopeat brick. Expands to 8–10 litres when soaked. Excellent water retention, aeration, and natural fungal resistance. Sustainable coconut by-product. Blend with compost and perlite for perfect potting mix.',
      price: 99, comparePrice: 149, stock: 200,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.soil,
      badges: ['650g block', 'Expands 8–10L', 'Eco-friendly'],
    },
    {
      name: 'Perlite 500g',
      slug: 'perlite-500g',
      description: 'Volcanic glass granules that dramatically improve drainage and aeration. Essential for succulents, cacti, and root-rot-prone plants. Lightweight, pH neutral, and reusable. Mix 20–30% into any potting soil.',
      price: 79, comparePrice: 120, stock: 150,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.soil,
      badges: ['500g', 'pH neutral', 'Reusable'],
    },
    {
      name: 'Premium Potting Mix 5kg',
      slug: 'premium-potting-mix-5kg',
      description: 'Ready-to-use potting mix for all indoor and outdoor plants. Blend of cocopeat, vermicompost, perlite, and neem powder. Well-draining, nutrient-rich, pest-treated. Just fill your pot and plant.',
      price: 249, comparePrice: 349, stock: 80,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.soil,
      badges: ['5kg', 'Ready to use', 'All plants'],
    },
    {
      name: 'Succulent & Cactus Mix 2kg',
      slug: 'succulent-cactus-mix-2kg',
      description: 'Fast-draining mix specially formulated for succulents and cacti. High perlite and coarse sand content prevents root rot. No amendments needed — ready to use straight from bag.',
      price: 179, comparePrice: 249, stock: 100,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.soil,
      badges: ['2kg', 'Fast-draining', 'Succulents & Cacti'],
    },
    // ── FERTILISER ────────────────────────────────────────────────────────────
    {
      name: 'Vermicompost 2kg',
      slug: 'vermicompost-2kg',
      description: 'Pure earthworm castings — richest natural fertilizer available. Contains NPK, micronutrients, beneficial bacteria, and natural growth hormones. Impossible to over-apply. Dramatically improves soil structure. Odourless, safe for indoor use.',
      price: 149, comparePrice: 199, stock: 120,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.fertiliser,
      badges: ['2kg', '100% Organic', 'Safe indoors'],
    },
    {
      name: 'Seaweed Extract Liquid 250ml',
      slug: 'seaweed-extract-liquid-250ml',
      description: 'Cold-pressed seaweed concentrate rich in natural growth hormones, trace minerals, and amino acids. Boosts root development, disease resistance, and stress tolerance. Dilute 2ml per litre. Use monthly as soil drench or foliar spray.',
      price: 199, comparePrice: 299, stock: 90,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.fertiliser,
      badges: ['250ml', 'Liquid concentrate', 'Organic'],
    },
    {
      name: 'Neem Oil 100ml',
      slug: 'neem-oil-100ml',
      description: 'Pure cold-pressed neem oil — India\'s traditional organic pesticide. Controls fungal diseases, aphids, mealybugs, spider mites, and whitefly. Safe for plants, beneficial insects, pets, and humans. Dilute 5ml per litre with a few drops of dish soap.',
      price: 149, comparePrice: 199, stock: 100,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.fertiliser,
      badges: ['100ml', 'Cold-pressed', 'Organic pesticide'],
    },
    {
      name: 'NPK 19-19-19 Fertilizer 500g',
      slug: 'npk-19-19-19-500g',
      description: 'Balanced water-soluble fertilizer with equal nitrogen, phosphorus, and potassium. Most versatile fertilizer for general plant growth. Dissolve 1g per litre, apply every 2–3 weeks. Suitable for all plants.',
      price: 129, comparePrice: 179, stock: 110,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.fertiliser,
      badges: ['500g', 'Water soluble', 'All plants'],
    },
    // ── POTS ──────────────────────────────────────────────────────────────────
    {
      name: 'Macramé Hanging Planter Set (3 pcs)',
      slug: 'macrame-hanging-planter-set-3',
      description: 'Handmade cotton macramé hanging planters in three sizes. Perfect for trailing plants like Pothos, String of Pearls, Ivy, and Ferns. Natural beige colour suits any decor. Includes hanging ring. Max 2kg each.',
      price: 399, comparePrice: 599, stock: 60,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.pots,
      badges: ['Set of 3', 'Handmade', 'Cotton macramé'],
    },
    {
      name: 'Terracotta Pot Set (4", 6", 8" with Saucers)',
      slug: 'terracotta-pot-set-with-saucers',
      description: 'Classic unglazed terracotta pots in three sizes — the best material for plant health. Porous walls prevent root rot. Regulates soil temperature naturally. Includes drainage holes and matching saucers.',
      price: 299, comparePrice: 449, stock: 80,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.pots,
      badges: ['Set of 3', 'With saucers', 'Drainage hole'],
    },
    {
      name: 'Fabric Grow Bags 5 Gallon (Pack of 5)',
      slug: 'fabric-grow-bags-5-gallon-pack-5',
      description: 'Non-woven breathable fabric grow bags for balcony and terrace gardens. Air-prunes roots for healthier growth. Folds flat for storage. Excellent for tomatoes, chillies, herbs, and small shrubs. Reusable for 3–5 seasons.',
      price: 249, comparePrice: 349, stock: 70,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.pots,
      badges: ['Pack of 5', '5 Gallon', 'Breathable fabric'],
    },
    // ── TOOLS ──────────────────────────────────────────────────────────────────
    {
      name: 'Bypass Pruning Shears',
      slug: 'bypass-pruning-shears',
      description: 'Professional SK5 stainless steel bypass pruner. Clean precise cuts that heal faster. Ergonomic non-slip handle with safety lock. Cuts stems up to 15mm. Essential for deadheading, shaping, and general plant maintenance.',
      price: 349, comparePrice: 499, stock: 70,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.tools,
      badges: ['SK5 steel', 'Safety lock', 'Up to 15mm'],
    },
    {
      name: 'Long Spout Watering Can 1.5L',
      slug: 'watering-can-1-5l-long-spout',
      description: 'Elegant long-spout watering can for indoor plants. Narrow spout delivers water precisely at root zone. 1.5L capacity ideal for balcony rounds. Rust-resistant with comfortable grip.',
      price: 249, comparePrice: 349, stock: 90,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.tools,
      badges: ['1.5L', 'Long spout', 'Indoor use'],
    },
    {
      name: 'Fine Mist Spray Bottle 500ml',
      slug: 'fine-mist-spray-bottle-500ml',
      description: 'Fine-mist spray for misting humidity-loving plants, foliar feeding, and applying neem solution. 360° nozzle works at any angle. Adjustable from fine mist to jet stream. Essential for ferns, calatheas, and tropicals.',
      price: 149, comparePrice: 199, stock: 120,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.tools,
      badges: ['500ml', 'Fine mist', '360° nozzle'],
    },
    // ── ACCESSORIES ────────────────────────────────────────────────────────────
    {
      name: 'USB Grow Light for Indoor Plants',
      slug: 'usb-grow-light-indoor',
      description: 'Full-spectrum LED grow light with flexible gooseneck and USB power. Provides red and blue wavelengths for photosynthesis. 3 light modes and auto timer (3h/9h/12h). Perfect for succulents, seedlings, and low-light Indian apartments. Clips onto pot or shelf.',
      price: 599, comparePrice: 999, stock: 45,
      thumbnailUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop'],
      category: SupplyCategory.accessories,
      badges: ['Full spectrum', 'Auto timer', 'USB powered'],
    },
  ]

  console.log(`\nAdding ${supplies.length} supplies...`)
  for (const supply of supplies) {
    const existing = await prisma.supply.findUnique({ where: { slug: supply.slug } })
    if (existing) { console.log(`  SKIP: ${supply.name}`); continue }
    await prisma.supply.create({ data: { ...supply, isActive: true } })
    console.log(`  ✓ ${supply.name}`)
  }

  console.log('\n✅ Catalog v2 complete!')
  console.log(`   Plants: ${plants.length} | Seeds: ${seeds.length} | Supplies: ${supplies.length}`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
