import { PrismaClient, PlantCategory, PlantDifficulty, SeedCategory } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {

  // ── NEW PLANTS ──────────────────────────────────────────────────────────────

  const plants = [
    {
      name: 'Parijat (Night Jasmine)',
      scientificName: 'Nyctanthes arbor-tristis',
      slug: 'parijat-night-jasmine',
      description: 'One of India\'s most beloved flowering trees. Parijat blooms nocturnally — tiny white flowers with an orange centre that fall like a carpet at dawn. Deeply sacred in Hindu tradition, mentioned in the Mahabharata. The fragrance is extraordinary. Grows as a large shrub or small tree; can be kept compact in a 12" pot for a balcony. Seasonal bloomer (Aug–Dec).',
      price: 349,
      comparePrice: 499,
      stock: 60,
      images: ['https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=800&h=800&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [PlantCategory.flowering, PlantCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['fragrant', 'night-blooming', 'sacred', 'indian-favourite', 'cultural', 'seasonal'],
      isBestseller: true,
      isNewArrival: false,
      careWatering: 'Water 2–3 times a week in summer, once a week in winter. Avoid waterlogging.',
      careSunlight: 'Full sun (6+ hours). South or west-facing balcony ideal.',
      careHumidity: 'Tolerates dry air well. No misting needed.',
      careTemperature: '18–35°C. Thrives in Indian summer heat. Protect from frost.',
      wateringIntervalDays: 3,
      fertiliserIntervalDays: 21,
      careGuide: {
        create: [
          { title: 'Watering', icon: '💧', body: 'Water deeply 2–3 times a week in summer. Allow top 1 inch of soil to dry between waterings. Reduce to weekly in winter.', order: 1 },
          { title: 'Sunlight', icon: '☀️', body: 'Needs full sun — at least 6 hours of direct sunlight. A south-facing balcony or open terrace is ideal.', order: 2 },
          { title: 'Flowering', icon: '🌸', body: 'Blooms appear from August to December. Flowers open at night and fall at dawn. Apply phosphorus-rich fertiliser (bone meal or DAP) in July to trigger flowering.', order: 3 },
          { title: 'Pruning', icon: '✂️', body: 'Prune lightly after the flowering season (January) to encourage bushy growth and more blooms next season.', order: 4 },
        ],
      },
    },
    {
      name: 'Raat Ki Rani (Night Blooming Jasmine)',
      scientificName: 'Cestrum nocturnum',
      slug: 'raat-ki-rani',
      description: 'Raat Ki Rani — Queen of the Night. This fast-growing shrub releases an intoxicating fragrance only after sunset, filling the entire neighbourhood. One of NurseryLive\'s top 5 bestsellers. Clusters of small creamy-white tubular flowers bloom repeatedly through the year. Perfect for balcony corners, gate-side planting, or large pots. Extremely low maintenance.',
      price: 299,
      comparePrice: 449,
      stock: 80,
      images: ['https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg?auto=compress&cs=tinysrgb&w=800&h=800&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [PlantCategory.flowering, PlantCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['fragrant', 'night-blooming', 'evergreen', 'fast-growing', 'low-maintenance', 'indian-favourite'],
      isBestseller: true,
      isNewArrival: false,
      careWatering: 'Water when the top inch of soil dries out. Very drought-tolerant once established.',
      careSunlight: 'Full sun to partial shade. Adapts well to most light conditions.',
      careHumidity: 'Tolerates both dry and humid conditions. No special humidity care needed.',
      careTemperature: '15–38°C. Extremely heat-tolerant. Ideal for Indian summers.',
      wateringIntervalDays: 4,
      fertiliserIntervalDays: 30,
      careGuide: {
        create: [
          { title: 'Watering', icon: '💧', body: 'Water when the top inch of soil feels dry. Once established, this plant is very drought-tolerant. Avoid standing water in the pot saucer.', order: 1 },
          { title: 'Sunlight', icon: '☀️', body: 'Thrives in full sun but adapts to partial shade. At least 4 hours of sunlight is ideal for maximum blooming.', order: 2 },
          { title: 'Fragrance Peak', icon: '🌙', body: 'The fragrance intensifies dramatically after 8 PM. Place near a window, seating area, or gate to enjoy the evening scent.', order: 3 },
          { title: 'Feeding', icon: '🧪', body: 'Feed monthly with a balanced liquid fertiliser during the growing season (March–October). A bloom booster in spring encourages heavier flowering.', order: 4 },
        ],
      },
    },
    {
      name: 'Dragon Fruit (Pitaya)',
      scientificName: 'Selenicereus undatus',
      slug: 'dragon-fruit-pitaya',
      description: 'Grow your own exotic dragon fruit on a terrace or balcony! This climbing cactus is surprisingly easy — it\'s drought-tolerant, needs very little soil, and produces striking pink-skinned fruits with white flesh. The flowers (which bloom at night) are among the most spectacular in the plant world. Needs a sturdy trellis or moss pole. Grafted plants fruit in 1–2 years.',
      price: 599,
      comparePrice: 899,
      stock: 40,
      images: ['https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=800&h=800&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [PlantCategory.fruit, PlantCategory.outdoor],
      difficulty: PlantDifficulty.intermediate,
      tags: ['exotic', 'terrace', 'cactus', 'night-blooming', 'grafted', 'trending', 'superfood'],
      isBestseller: false,
      isNewArrival: true,
      careWatering: 'Water deeply once a week. Dragon fruit is a cactus — it hates overwatering. Allow soil to dry completely between waterings.',
      careSunlight: 'Full sun — 6–8 hours minimum. Does not fruit well in shade.',
      careHumidity: 'Tolerates low humidity. No misting needed.',
      careTemperature: '20–38°C. Thrives in Indian heat. Protect from frost.',
      wateringIntervalDays: 7,
      fertiliserIntervalDays: 30,
      careGuide: {
        create: [
          { title: 'Watering', icon: '💧', body: 'Water once a week deeply; let the soil dry completely before the next watering. Dragon fruit is a cactus — root rot from overwatering is the #1 killer.', order: 1 },
          { title: 'Support', icon: '🪵', body: 'Needs a strong trellis, cement post, or large moss pole (5–6 ft). The plant climbs via aerial roots — tie young stems loosely.', order: 2 },
          { title: 'Sunlight', icon: '☀️', body: 'Requires 6–8 hours of direct sun. Terrace or south-facing garden preferred. Won\'t fruit in partial shade.', order: 3 },
          { title: 'Fruiting', icon: '🐉', body: 'Grafted plants flower in 1–2 years. Flowers bloom overnight — hand-pollinate with a soft brush between two flowers in the same night for best fruit set.', order: 4 },
        ],
      },
    },
  ]

  for (const p of plants) {
    const exists = await prisma.plant.findUnique({ where: { slug: p.slug } })
    if (exists) { console.log(`⏭  Plant exists: ${p.name}`); continue }
    await prisma.plant.create({ data: p as any })
    console.log(`✅ Plant added: ${p.name}`)
  }

  // ── NEW SEEDS ───────────────────────────────────────────────────────────────

  const seeds = [
    {
      name: 'Karela (Bitter Gourd) Seeds',
      scientificName: 'Momordica charantia',
      slug: 'seeds-karela-bitter-gourd',
      description: 'The most medicinal vegetable in Indian kitchens. Grow your own bitter gourd on a trellis or balcony railing — it\'s a fast-climbing vine that fruits prolifically. Essential for managing blood sugar; used in countless Indian recipes and Ayurvedic preparations. Sow in warm weather (March–July). Each vine gives 20–30 fruits per season.',
      price: 59,
      comparePrice: 89,
      stock: 400,
      images: ['https://images.pexels.com/photos/4033471/pexels-photo-4033471.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/4033471/pexels-photo-4033471.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [SeedCategory.vegetable, SeedCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['gourd', 'monsoon', 'trellis', 'medicinal', 'ayurvedic', 'diabetic-friendly'],
      isBestseller: true,
      isNewArrival: false,
      germinationDays: '5–7 days',
      sowingDepth: '1–2 cm deep',
      sowingMethod: 'Soak seeds 24 hrs, sow 2 seeds per hole 1 cm deep. Thin to 1 plant.',
      harvestDays: '55–65 days',
      seedsPerPacket: 15,
      sowingSeason: 'Feb–June (summer/monsoon)',
    },
    {
      name: 'Lauki (Bottle Gourd) Seeds',
      scientificName: 'Lagenaria siceraria',
      slug: 'seeds-lauki-bottle-gourd',
      description: 'One of India\'s most widely grown home vegetables. Lauki (bottle gourd) is a fast-climbing vine perfect for terrace trellis or pergola growing. Light, digestible, and used in everything from sabzi to halwa to juice. Extremely productive — a single vine can produce 15–25 gourds. Thrives in summer heat.',
      price: 49,
      comparePrice: 79,
      stock: 500,
      images: ['https://images.pexels.com/photos/4033471/pexels-photo-4033471.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/4033471/pexels-photo-4033471.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [SeedCategory.vegetable, SeedCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['gourd', 'monsoon', 'trellis', 'summer', 'productive', 'indian-staple'],
      isBestseller: true,
      isNewArrival: false,
      germinationDays: '4–6 days',
      sowingDepth: '1–2 cm deep',
      sowingMethod: 'Soak seeds 12 hrs, sow directly 1–2 cm deep. Provide trellis immediately.',
      harvestDays: '50–70 days',
      seedsPerPacket: 15,
      sowingSeason: 'Feb–July (summer/early monsoon)',
    },
    {
      name: 'Ridge Gourd (Turai) Seeds',
      scientificName: 'Luffa acutangula',
      slug: 'seeds-ridge-gourd-turai',
      description: 'The quick-growing monsoon climber that thrives on any trellis. Ridge gourd (turai) is light, nutritious, and one of the easiest vegetables to grow in Indian summers. Harvest young (15–18 cm) for best flavour. Overgrown fruits dry into natural loofah sponges — a zero-waste bonus. A single vine covers a full balcony trellis.',
      price: 49,
      comparePrice: 79,
      stock: 400,
      images: ['https://images.pexels.com/photos/4033471/pexels-photo-4033471.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/4033471/pexels-photo-4033471.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [SeedCategory.vegetable, SeedCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['gourd', 'monsoon', 'trellis', 'loofah', 'fast-growing', 'summer'],
      isBestseller: false,
      isNewArrival: false,
      germinationDays: '4–6 days',
      sowingDepth: '1 cm deep',
      sowingMethod: 'Sow directly 1 cm deep near a trellis. Soak seeds 8 hrs for faster germination.',
      harvestDays: '45–55 days',
      seedsPerPacket: 15,
      sowingSeason: 'March–July',
    },
    {
      name: 'Zinnia (Mixed Colours) Seeds',
      scientificName: 'Zinnia elegans',
      slug: 'seeds-zinnia-mixed',
      description: 'The easiest summer flower you can grow — zinnias go from seed to full bloom in under 8 weeks. These cheerful daisy-like flowers in red, orange, pink, yellow, and white attract butterflies and bloom continuously through summer. Excellent for cut flower arrangements and butterfly gardens. One of the highest bang-for-buck flower seeds available.',
      price: 69,
      comparePrice: 99,
      stock: 600,
      images: ['https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [SeedCategory.flowering, SeedCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['summer-flower', 'butterfly-garden', 'cut-flower', 'fast-blooming', 'colourful', 'heat-tolerant'],
      isBestseller: true,
      isNewArrival: false,
      germinationDays: '5–7 days',
      sowingDepth: '0.5 cm deep',
      sowingMethod: 'Sow directly in final position or tray. Press seeds lightly into moist soil. Thin to 20 cm apart.',
      harvestDays: '50–60 days to first bloom',
      seedsPerPacket: 30,
      sowingSeason: 'Feb–April (summer) or Sept–Oct (winter)',
    },
    {
      name: 'Cosmos (Mixed) Seeds',
      scientificName: 'Cosmos bipinnatus',
      slug: 'seeds-cosmos-mixed',
      description: 'Feathery, airy cosmos flowers — pink, white, magenta, and crimson — sway elegantly on tall stems. One of the easiest flowers from seed; practically grows itself once established. Perfect for filling large balcony pots or garden beds with colour from October to February. Excellent butterfly and bee magnet. Blooms continuously; cut flowers last 5–7 days in a vase.',
      price: 69,
      comparePrice: 99,
      stock: 500,
      images: ['https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [SeedCategory.flowering, SeedCategory.outdoor],
      difficulty: PlantDifficulty.beginner,
      tags: ['winter-flower', 'butterfly-garden', 'cut-flower', 'airy', 'self-seeds', 'easy'],
      isBestseller: false,
      isNewArrival: true,
      germinationDays: '5–10 days',
      sowingDepth: '0.5 cm deep',
      sowingMethod: 'Scatter seeds on moist soil, press gently, water lightly. Thin to 30 cm apart.',
      harvestDays: '60–70 days to first bloom',
      seedsPerPacket: 30,
      sowingSeason: 'Sept–Nov (winter/spring)',
    },
    {
      name: 'Lotus Seeds',
      scientificName: 'Nelumbo nucifera',
      slug: 'seeds-lotus',
      description: 'Grow the sacred Indian lotus in a pot! Lotus seeds germinate reliably in 3–5 days and plants bloom in the same season. All you need is a wide, shallow container (no drainage hole) filled with water and garden soil. Sacred in Hindu and Buddhist traditions, the lotus represents purity and enlightenment. One of the most unique and rewarding plants to grow from seed.',
      price: 199,
      comparePrice: 299,
      stock: 200,
      images: ['https://images.pexels.com/photos/3887985/pexels-photo-3887985.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      thumbnailUrl: 'https://images.pexels.com/photos/3887985/pexels-photo-3887985.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      categories: [SeedCategory.flowering, SeedCategory.outdoor],
      difficulty: PlantDifficulty.intermediate,
      tags: ['sacred', 'aquatic', 'water-plant', 'unique', 'cultural', 'spiritual', 'india'],
      isBestseller: false,
      isNewArrival: true,
      germinationDays: '3–5 days',
      sowingDepth: 'Nick seed coat, soak in warm water',
      sowingMethod: 'Nick the hard seed coat with a file, soak in warm water changing daily until sprout appears, then plant in muddy water container.',
      harvestDays: '90–120 days to bloom',
      seedsPerPacket: 5,
      sowingSeason: 'March–June (warm weather only)',
    },
  ]

  for (const s of seeds) {
    const exists = await prisma.seed.findUnique({ where: { slug: s.slug } })
    if (exists) { console.log(`⏭  Seed exists: ${s.name}`); continue }
    await prisma.seed.create({ data: s as any })
    console.log(`✅ Seed added: ${s.name}`)
  }

  // ── NEW SUPPLIES ─────────────────────────────────────────────────────────────

  const supplies = [
    {
      name: 'Neem Cake Powder 1kg',
      slug: 'neem-cake-powder-1kg',
      description: 'Cold-pressed neem cake — the residue after extracting neem oil — is one of the most powerful organic soil amendments. It suppresses soil fungal diseases, repels nematodes and soil pests, and slowly releases nitrogen over 3–4 months. Use as a soil drench or top dressing. Safe for vegetables, herbs, and fruiting plants. 100% organic, chemical-free.',
      price: 199,
      comparePrice: 299,
      stock: 300,
      thumbnailUrl: 'https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'fertiliser',
      badges: ['organic', 'pest-repellent', 'slow-release'],
    },
    {
      name: 'Banana Peel Fertilizer 500g',
      slug: 'banana-peel-fertilizer-500g',
      description: 'Upcycled banana peels slow-dried and powdered into a potassium and phosphorus-rich organic fertiliser. Potassium is essential for flowering, fruiting, and strong root development. Banana peel fertiliser is particularly effective for flowering plants (hibiscus, roses, mogra), fruiting plants (tomato, chilli), and succulents. Just 1 tablespoon per pot every 2 weeks.',
      price: 149,
      comparePrice: 229,
      stock: 250,
      thumbnailUrl: 'https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'fertiliser',
      badges: ['organic', 'upcycled', 'potassium-rich'],
    },
    {
      name: 'Bone Meal 1kg',
      slug: 'bone-meal-1kg',
      description: 'Steamed bone meal — the slow-release phosphorus source trusted by Indian home gardeners for decades. Phosphorus drives root development, flower bud formation, and fruit setting. Mix into potting soil at planting time or top-dress monthly. Particularly effective for roses, fruit trees, and root vegetables. Works best in soil with good moisture.',
      price: 179,
      comparePrice: 249,
      stock: 200,
      thumbnailUrl: 'https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'fertiliser',
      badges: ['organic', 'phosphorus-rich', 'slow-release'],
    },
    {
      name: 'Coir Moss Stick 2ft',
      slug: 'coir-moss-stick-2ft',
      description: 'The must-have support for climbing indoor plants. Philodendrons, pothos, monsteras, syngonium, and money plants all climb naturally in the wild — a moss stick lets them express this instinct, leading to larger leaves, better growth, and a healthier plant. Made from natural coir fibre wrapped around a PVC pipe. Stays moist to encourage aerial root attachment.',
      price: 149,
      comparePrice: 199,
      stock: 400,
      thumbnailUrl: 'https://images.pexels.com/photos/4750274/pexels-photo-4750274.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/4750274/pexels-photo-4750274.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'accessories',
      badges: ['natural-coir', 'indoor-essential', 'reusable'],
    },
    {
      name: 'Coir Moss Stick 3ft',
      slug: 'coir-moss-stick-3ft',
      description: 'Taller version for mature climbing plants. Ideal for large monstera, pothos towers, philodendron gloriosum, and syngonium that have already outgrown a 2ft support. The coir fibre holds moisture — mist the stick when watering your plant to encourage healthy aerial root development. Leaves noticeably increase in size once the plant starts climbing.',
      price: 199,
      comparePrice: 299,
      stock: 300,
      thumbnailUrl: 'https://images.pexels.com/photos/4750274/pexels-photo-4750274.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/4750274/pexels-photo-4750274.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'accessories',
      badges: ['natural-coir', 'large-plants', 'premium'],
    },
    {
      name: 'Terrarium Kit (DIY)',
      slug: 'terrarium-kit-diy',
      description: 'Everything you need to build your own miniature garden in glass. Kit includes: glass terrarium bowl (25cm diameter), layer of pebbles for drainage, horticultural charcoal to prevent odour, premium mossy potting mix, and 3 small plants (assorted — fittonia, mini fern, peperomia). Just layer, plant, and display. Makes a beautiful gift. No watering for weeks.',
      price: 899,
      comparePrice: 1299,
      stock: 80,
      thumbnailUrl: 'https://images.pexels.com/photos/1903965/pexels-photo-1903965.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/1903965/pexels-photo-1903965.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'pots',
      badges: ['gift-ready', 'diy-kit', 'self-sustaining'],
    },
    {
      name: 'Self-Watering Planter 8"',
      slug: 'self-watering-planter-8inch',
      description: 'Never over-water or under-water again. This double-chamber planter has a water reservoir at the bottom — plants draw up exactly what they need via a wicking system. One fill lasts 7–14 days depending on the plant. Perfect for busy urbanites, frequent travellers, or anyone who kills plants by forgetting to water. Works beautifully for herbs, ferns, peace lily, and pothos.',
      price: 499,
      comparePrice: 749,
      stock: 150,
      thumbnailUrl: 'https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'pots',
      badges: ['self-watering', 'travel-friendly', 'beginner-safe'],
    },
    {
      name: 'Self-Watering Planter 12"',
      slug: 'self-watering-planter-12inch',
      description: 'The larger version of our self-watering planter — ideal for tomatoes, chillies, curry leaf, tulsi, and medium indoor plants. The water reservoir holds enough for 10–15 days without refilling. A water level indicator shows when to refill. Made from UV-stabilised food-grade plastic — safe for vegetables. Includes a drainage plug for outdoor use in monsoon.',
      price: 699,
      comparePrice: 999,
      stock: 120,
      thumbnailUrl: 'https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'pots',
      badges: ['self-watering', 'food-safe', 'uv-stabilised'],
    },
    {
      name: 'Fabric Grow Bag 10 Gallon (Pack of 3)',
      slug: 'fabric-grow-bag-10-gallon-3pack',
      description: 'The go-to container for terrace vegetable gardens. Fabric grow bags air-prune roots — when roots reach the breathable walls they stop growing and branch back, creating a dense, fibrous root system that outperforms plastic pots. Perfect for tomatoes, chillies, brinjal, and herbs. Foldable for off-season storage. UV-stabilised, BPA-free geotextile fabric. Pack of 3.',
      price: 299,
      comparePrice: 449,
      stock: 300,
      thumbnailUrl: 'https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'pots',
      badges: ['air-pruning', 'pack-of-3', 'terrace-garden'],
    },
    {
      name: '5-Piece Garden Tool Kit',
      slug: 'garden-tool-kit-5piece',
      description: 'The complete starter kit for home gardeners. Includes: hand trowel, transplanter, cultivator/weeder, hand fork, and folding pruner — all with ergonomic non-slip handles and rust-resistant stainless steel heads. Comes in a zipper carry pouch. Everything you need to pot, plant, prune, and weed. Makes a thoughtful gift for anyone starting their garden journey.',
      price: 549,
      comparePrice: 799,
      stock: 200,
      thumbnailUrl: 'https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'tools',
      badges: ['complete-kit', 'gift-ready', 'stainless-steel'],
    },
    {
      name: 'Ceramic Pot with Saucer 6"',
      slug: 'ceramic-pot-with-saucer-6inch',
      description: 'Elegant glazed ceramic pot with matching drainage saucer. The earthy, matte finish complements any home interior — from boho to minimal to industrial. The drainage hole prevents root rot while the saucer catches excess water to protect your floors and furniture. Pairs beautifully with succulents, cacti, peperomia, or snake plants. Weight: ~800g. Available in terracotta, sage green, and off-white.',
      price: 349,
      comparePrice: 499,
      stock: 250,
      thumbnailUrl: 'https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'pots',
      badges: ['with-saucer', 'decorative', 'drainage-hole'],
    },
    {
      name: 'Ceramic Pot with Saucer 8"',
      slug: 'ceramic-pot-with-saucer-8inch',
      description: 'The medium-size ceramic pot that fits on any windowsill, console table, or bookshelf. With a matching glazed saucer, it\'s both functional and beautiful. A drainage hole at the base prevents the most common cause of plant death — waterlogging. Suitable for pothos, philodendron, monstera (young), peace lily, and medium herbs. Slightly heavier build for stability.',
      price: 499,
      comparePrice: 699,
      stock: 200,
      thumbnailUrl: 'https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
      images: ['https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop'],
      category: 'pots',
      badges: ['with-saucer', 'decorative', 'medium'],
    },
  ]

  for (const s of supplies) {
    const exists = await prisma.supply.findUnique({ where: { slug: s.slug } })
    if (exists) { console.log(`⏭  Supply exists: ${s.name}`); continue }
    await prisma.supply.create({ data: s as any })
    console.log(`✅ Supply added: ${s.name}`)
  }

  console.log('\n🎉 Done! India catalog expansion complete.')
}

main().catch(console.error).finally(() => prisma.$disconnect())
