/**
 * seed-seeds.ts — Populate the Seed catalog
 * Run: npx tsx prisma/seed-seeds.ts
 *
 * Same category taxonomy as plants:
 * indoor | outdoor | succulent | tropical | herb | flowering |
 * fern | air_purifying | bonsai | vegetable | fruit
 */
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

const P = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop`
const U = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=600&h=600&q=80`

const seeds = [
  // ─── VEGETABLES ──────────────────────────────────────────────────────────
  {
    name: 'Tomato (Cherry Mix) Seeds',
    scientificName: 'Solanum lycopersicum var. cerasiforme',
    slug: 'seeds-cherry-tomato',
    description: 'Mixed cherry tomato seeds — red, yellow, and orange — that produce hundreds of sweet bite-sized fruits in pots and grow bags. The most productive vegetable you can grow on a balcony. One packet gives 6–8 plants.',
    price: 59, comparePrice: 89, stock: 300,
    thumbnailUrl: P(3735739), images: [P(3735739)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['high-yield', 'pot-friendly', 'grow-bag', 'mixed-colours'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '5–8 days', sowingDepth: '0.5 cm', sowingMethod: 'Seedling tray, then transplant',
    harvestDays: '65–75 days', seedsPerPacket: 30, sowingSeason: 'Sep–Nov, Jan–Feb',
    linkedPlantSlug: 'cherry-tomato',
  },
  {
    name: 'Capsicum (Mixed Colours) Seeds',
    scientificName: 'Capsicum annuum',
    slug: 'seeds-capsicum-mixed',
    description: 'Grow your own green, red, and yellow bell peppers from seed. A single packet produces 6–8 robust plants that yield sweet, crisp capsicums continuously for 6–8 months in grow bags on your balcony.',
    price: 69, comparePrice: 99, stock: 250,
    thumbnailUrl: P(3735739), images: [P(3735739)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['high-yield', 'grow-bag', 'mixed-colours', 'kitchen-essential'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '8–12 days', sowingDepth: '1 cm', sowingMethod: 'Seedling tray, then transplant',
    harvestDays: '70–80 days', seedsPerPacket: 25, sowingSeason: 'Aug–Oct, Jan–Feb',
    linkedPlantSlug: 'capsicum-bell-pepper',
  },
  {
    name: 'Chilli (Jwala Hot) Seeds',
    scientificName: 'Capsicum annuum',
    slug: 'seeds-chilli-jwala',
    description: 'Jwala is India\'s most popular thin green chilli — fiery, flavourful, and prolific. One plant in a pot produces hundreds of chillies per season. These are the real deal from authentic Indian heirloom varieties.',
    price: 39, comparePrice: 59, stock: 400,
    thumbnailUrl: P(1999268), images: [P(1999268)],
    categories: ['vegetable', 'herb', 'outdoor'],
    difficulty: 'beginner', tags: ['kitchen-essential', 'high-yield', 'heirloom', 'hot'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '7–10 days', sowingDepth: '0.5 cm', sowingMethod: 'Direct sow or seedling tray',
    harvestDays: '60–70 days', seedsPerPacket: 40, sowingSeason: 'Feb–Apr, Aug–Sep',
    linkedPlantSlug: 'chilli-mirchi',
  },
  {
    name: 'Spinach (Palak) Seeds',
    scientificName: 'Spinacia oleracea',
    slug: 'seeds-spinach-palak',
    description: 'Sow directly in any shallow container or grow bag and harvest fresh palak in just 30 days. Far more nutritious than store-bought spinach that is days old. One packet fills a large balcony window box.',
    price: 29, comparePrice: 49, stock: 500,
    thumbnailUrl: U('1576045057995-568f588f82fb'), images: [U('1576045057995-568f588f82fb')],
    categories: ['vegetable', 'herb', 'outdoor'],
    difficulty: 'beginner', tags: ['fast-harvest', 'cut-and-come-again', 'pot-friendly', 'nutritious'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '4–7 days', sowingDepth: '1 cm', sowingMethod: 'Direct sow',
    harvestDays: '25–35 days', seedsPerPacket: 100, sowingSeason: 'Oct–Feb',
    linkedPlantSlug: 'spinach-palak',
  },
  {
    name: 'Radish (Mooli) Seeds',
    scientificName: 'Raphanus sativus',
    slug: 'seeds-radish-mooli',
    description: 'The fastest vegetable in the garden — crisp, peppery radishes ready in just 25 days! Direct-sow in any 20 cm deep pot or grow bag. Great for first-time growers and kids.',
    price: 25, comparePrice: 39, stock: 500,
    thumbnailUrl: P(1435904), images: [P(1435904)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['fast-harvest', 'direct-sow', 'beginner-friendly', 'kids'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '3–5 days', sowingDepth: '1 cm', sowingMethod: 'Direct sow',
    harvestDays: '25–30 days', seedsPerPacket: 80, sowingSeason: 'Oct–Feb',
    linkedPlantSlug: 'radish-mooli',
  },
  {
    name: 'Cucumber Seeds',
    scientificName: 'Cucumis sativus',
    slug: 'seeds-cucumber',
    description: 'Train cucumbers up a balcony trellis for a space-efficient harvest — one plant gives 20–30 cucumbers. The compact "Poinsett" and "Pusa Uday" varieties are best for pot and grow bag growing.',
    price: 45, comparePrice: 65, stock: 300,
    thumbnailUrl: P(2329440), images: [P(2329440)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['vertical-grow', 'grow-bag', 'high-yield', 'trellis'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '4–7 days', sowingDepth: '1.5 cm', sowingMethod: 'Direct sow or seedling tray',
    harvestDays: '50–60 days', seedsPerPacket: 20, sowingSeason: 'Feb–Apr, Jul–Aug',
    linkedPlantSlug: 'cucumber',
  },
  {
    name: 'French Beans Seeds',
    scientificName: 'Phaseolus vulgaris',
    slug: 'seeds-french-beans',
    description: 'Bush-type French beans that need no staking and fit neatly in 12L grow bags. They fix nitrogen in the soil, making them excellent companion plants. High yield, low fuss.',
    price: 39, comparePrice: 59, stock: 300,
    thumbnailUrl: P(1435904), images: [P(1435904)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['bush-type', 'no-staking', 'nitrogen-fixer', 'grow-bag'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '5–8 days', sowingDepth: '2 cm', sowingMethod: 'Direct sow',
    harvestDays: '50–60 days', seedsPerPacket: 30, sowingSeason: 'Sep–Nov, Jan–Mar',
    linkedPlantSlug: 'french-beans',
  },
  {
    name: 'Peas (Matar) Seeds',
    scientificName: 'Pisum sativum',
    slug: 'seeds-peas-matar',
    description: 'Sweet, fresh, straight-from-the-pod peas are a winter luxury. These climbing varieties use vertical space efficiently on any balcony string trellis. Nothing beats fresh matar from your own garden.',
    price: 35, comparePrice: 55, stock: 400,
    thumbnailUrl: P(3735739), images: [P(3735739)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['winter-crop', 'climber', 'sweet', 'trellis'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '5–8 days', sowingDepth: '2 cm', sowingMethod: 'Direct sow',
    harvestDays: '60–70 days', seedsPerPacket: 40, sowingSeason: 'Oct–Dec',
    linkedPlantSlug: 'peas-matar',
  },
  {
    name: 'Beetroot Seeds',
    scientificName: 'Beta vulgaris',
    slug: 'seeds-beetroot',
    description: 'One of the best root vegetables for container growing. Beetroot seeds are actually seed clusters — each produces 2–3 plants. Both the roots and the stunning red leaves are edible and nutritious.',
    price: 35, comparePrice: 55, stock: 300,
    thumbnailUrl: P(1435904), images: [P(1435904)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['root-vegetable', 'edible-leaves', 'pot-friendly', 'nutritious'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '5–10 days', sowingDepth: '1 cm', sowingMethod: 'Direct sow',
    harvestDays: '55–70 days', seedsPerPacket: 50, sowingSeason: 'Oct–Feb',
    linkedPlantSlug: 'beetroot',
  },
  {
    name: 'Carrot (Chantenay) Seeds',
    scientificName: 'Daucus carota',
    slug: 'seeds-carrot-chantenay',
    description: 'Chantenay is the best carrot variety for pot and grow bag growing — short, broad shoulders (15 cm) that develop perfectly in 25 cm deep containers. Sweet, crunchy, and a joy to grow.',
    price: 39, comparePrice: 59, stock: 300,
    thumbnailUrl: P(1435904), images: [P(1435904)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['container-variety', 'short-root', 'pot-friendly', 'sweet'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '7–14 days', sowingDepth: '0.5 cm', sowingMethod: 'Direct sow (no transplanting)',
    harvestDays: '65–75 days', seedsPerPacket: 100, sowingSeason: 'Oct–Jan',
    linkedPlantSlug: 'carrot',
  },
  {
    name: 'Lettuce (Lollo Rossa) Seeds',
    scientificName: 'Lactuca sativa',
    slug: 'seeds-lettuce-lollo-rossa',
    description: 'A beautiful red-tipped loose-leaf lettuce perfect for window boxes and balcony troughs. Harvest outer leaves continuously for months — one of the few "cut-and-come-again" vegetables.',
    price: 45, comparePrice: 65, stock: 250,
    thumbnailUrl: P(2286776), images: [P(2286776)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['cut-and-come-again', 'window-box', 'winter-crop', 'ornamental'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '3–7 days', sowingDepth: '0.3 cm', sowingMethod: 'Surface sow, press gently',
    harvestDays: '28–45 days', seedsPerPacket: 200, sowingSeason: 'Sep–Feb',
    linkedPlantSlug: 'lettuce-salad',
  },
  {
    name: 'Bhindi (Okra) Seeds',
    scientificName: 'Abelmoschus esculentus',
    slug: 'seeds-bhindi-okra',
    description: 'Bhindi is one of the most rewarding summer vegetables for Indian balconies. Plants grow 60–80 cm tall in a 20L grow bag and produce pods continuously through the hot months. Harvest daily for maximum production.',
    price: 35, comparePrice: 49, stock: 400,
    thumbnailUrl: P(3511755), images: [P(3511755)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['summer-crop', 'heat-tolerant', 'high-yield', 'grow-bag'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '5–8 days', sowingDepth: '2 cm', sowingMethod: 'Direct sow (soak overnight first)',
    harvestDays: '50–60 days', seedsPerPacket: 30, sowingSeason: 'Feb–May',
    linkedPlantSlug: 'bhindi-okra',
  },
  {
    name: 'Brinjal (Eggplant) Seeds',
    scientificName: 'Solanum melongena',
    slug: 'seeds-brinjal',
    description: 'Brinjal grows well in large containers (20L+) on balconies and terraces. Long, slender "Pusa Kranti" or round "Pusa Purple Round" varieties are most compact. Fruits continuously for months in warm Indian weather.',
    price: 39, comparePrice: 59, stock: 250,
    thumbnailUrl: P(1407305), images: [P(1407305)],
    categories: ['vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['container-variety', 'heat-tolerant', 'grow-bag', 'productive'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '7–12 days', sowingDepth: '0.5 cm', sowingMethod: 'Seedling tray, then transplant',
    harvestDays: '70–80 days', seedsPerPacket: 30, sowingSeason: 'Jan–Mar, Jun–Aug',
    linkedPlantSlug: 'brinjal-eggplant',
  },

  // ─── HERBS ───────────────────────────────────────────────────────────────
  {
    name: 'Coriander (Dhania) Seeds',
    scientificName: 'Coriandrum sativum',
    slug: 'seeds-coriander',
    description: 'Fresh coriander from your windowsill — always available, always fragrant, always free. Sow a new batch every 2 weeks for continuous supply. Use the whole plant: leaves for garnishing, dried seeds as a spice.',
    price: 25, comparePrice: 39, stock: 600,
    thumbnailUrl: P(4033471), images: [P(4033471)],
    categories: ['herb', 'outdoor'],
    difficulty: 'beginner', tags: ['windowsill', 'kitchen-essential', 'fast-growing', 'succession-sowing'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '5–10 days', sowingDepth: '1 cm', sowingMethod: 'Direct sow (crush seed lightly first)',
    harvestDays: '25–30 days', seedsPerPacket: 100, sowingSeason: 'Sep–Feb (all year in mild climates)',
    linkedPlantSlug: 'coriander-dhania',
  },
  {
    name: 'Methi (Fenugreek) Seeds',
    scientificName: 'Trigonella foenum-graecum',
    slug: 'seeds-methi-fenugreek',
    description: 'Methi is India\'s most nutritious kitchen herb and one of the easiest to grow. Sow thickly in any container, harvest as microgreens in 10 days or full leaves in 25 days. Both leaves and seeds are used in cooking.',
    price: 25, comparePrice: 39, stock: 600,
    thumbnailUrl: P(2286776), images: [P(2286776)],
    categories: ['herb', 'vegetable', 'outdoor'],
    difficulty: 'beginner', tags: ['microgreens', 'fast-harvest', 'medicinal', 'kitchen-essential'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '2–4 days', sowingDepth: '0.5 cm', sowingMethod: 'Direct sow densely',
    harvestDays: '10–25 days', seedsPerPacket: 150, sowingSeason: 'Sep–Feb',
    linkedPlantSlug: 'methi-fenugreek',
  },
  {
    name: 'Tulsi (Holy Basil) Seeds',
    scientificName: 'Ocimum tenuiflorum',
    slug: 'seeds-tulsi',
    description: 'Grow your own Tulsi — the sacred herb of Indian households — from seed. Tiny seeds germinate quickly and grow into a lush, fragrant plant. Used daily in tea, religious rituals, and Ayurvedic medicine.',
    price: 29, comparePrice: 45, stock: 400,
    thumbnailUrl: P(1072824), images: [P(1072824)],
    categories: ['herb', 'outdoor'],
    difficulty: 'beginner', tags: ['sacred', 'medicinal', 'ayurvedic', 'fragrant', 'vastu'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '5–10 days', sowingDepth: 'Surface sow', sowingMethod: 'Press onto moist soil surface, do not cover',
    harvestDays: '45–60 days', seedsPerPacket: 100, sowingSeason: 'Mar–Jun (after winter)',
    linkedPlantSlug: 'tulsi-holy-basil',
  },
  {
    name: 'Sweet Basil Seeds',
    scientificName: 'Ocimum basilicum',
    slug: 'seeds-sweet-basil',
    description: 'Italian sweet basil with large, aromatic leaves — perfect for home cooking, pasta sauces, and fresh salads. Easy to grow on a sunny windowsill. Sow every 4–6 weeks for continuous fresh leaves.',
    price: 35, comparePrice: 55, stock: 350,
    thumbnailUrl: P(1072824), images: [P(1072824)],
    categories: ['herb', 'outdoor'],
    difficulty: 'beginner', tags: ['culinary', 'fragrant', 'windowsill', 'italian-cooking'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '5–8 days', sowingDepth: '0.3 cm', sowingMethod: 'Seedling tray or direct sow',
    harvestDays: '30–40 days', seedsPerPacket: 80, sowingSeason: 'Mar–Aug',
    linkedPlantSlug: 'sweet-basil',
  },
  {
    name: 'Pudina (Mint) Seeds',
    scientificName: 'Mentha spicata',
    slug: 'seeds-mint-pudina',
    description: 'Grow your own fresh mint for chai, chutneys, lemonade, and raita. Mint from seed is slower than cuttings, but this packet gives you the start of an endless mint supply — one plant propagates freely forever.',
    price: 35, comparePrice: 55, stock: 300,
    thumbnailUrl: P(3076899), images: [P(3076899)],
    categories: ['herb', 'outdoor'],
    difficulty: 'beginner', tags: ['culinary', 'medicinal', 'fragrant', 'tea-herb'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '7–14 days', sowingDepth: 'Surface sow', sowingMethod: 'Press onto moist soil, do not cover — needs light to germinate',
    harvestDays: '45–60 days', seedsPerPacket: 200, sowingSeason: 'Feb–May, Aug–Oct',
    linkedPlantSlug: 'mint-pudina',
  },
  {
    name: 'Curry Leaf (Kadi Patta) Seeds',
    scientificName: 'Murraya koenigii',
    slug: 'seeds-curry-leaf',
    description: 'Grow your own curry leaf tree from seed. Fresh curry leaves have an incomparably stronger flavour than dried or store-bought leaves. The plant is evergreen and produces fragrant leaves year-round once established.',
    price: 49, comparePrice: 79, stock: 200,
    thumbnailUrl: P(4198852), images: [P(4198852)],
    categories: ['herb', 'outdoor'],
    difficulty: 'intermediate', tags: ['kitchen-essential', 'evergreen', 'south-indian', 'long-term'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '14–21 days', sowingDepth: '1 cm', sowingMethod: 'Fresh seeds only — use immediately after extracting from berry',
    harvestDays: '180+ days (2–3 years for full harvest)', seedsPerPacket: 10, sowingSeason: 'Feb–May',
    linkedPlantSlug: 'curry-leaf',
  },
  {
    name: 'Lemongrass Seeds',
    scientificName: 'Cymbopogon citratus',
    slug: 'seeds-lemongrass',
    description: 'Grow aromatic, mosquito-repelling lemongrass from seed. Used fresh in chai, Thai curries, and herbal teas — and the scent naturally deters mosquitoes from your balcony.',
    price: 39, comparePrice: 59, stock: 250,
    thumbnailUrl: P(3076899), images: [P(3076899)],
    categories: ['herb', 'outdoor'],
    difficulty: 'beginner', tags: ['mosquito-repellent', 'culinary', 'tea-herb', 'fragrant'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '10–14 days', sowingDepth: '0.3 cm', sowingMethod: 'Seedling tray (surface sow, barely cover)',
    harvestDays: '90–120 days', seedsPerPacket: 50, sowingSeason: 'Mar–Jun',
    linkedPlantSlug: 'lemongrass',
  },

  // ─── FLOWERING ───────────────────────────────────────────────────────────
  {
    name: 'Marigold (African Tall Mix) Seeds',
    scientificName: 'Tagetes erecta',
    slug: 'seeds-marigold-african',
    description: 'Large, lush African marigold seeds in a mixed colour pack — bright orange, yellow, and bi-colour. Germinate in 5 days, bloom in 50 days. Repel pests naturally. One packet fills a whole balcony with colour.',
    price: 29, comparePrice: 45, stock: 500,
    thumbnailUrl: P(3976258), images: [P(3976258)],
    categories: ['flowering', 'outdoor'],
    difficulty: 'beginner', tags: ['pest-repellent', 'fast-blooming', 'mixed-colours', 'direct-sow'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '4–7 days', sowingDepth: '0.5 cm', sowingMethod: 'Direct sow or seedling tray',
    harvestDays: '45–55 days', seedsPerPacket: 50, sowingSeason: 'Aug–Nov, Jan–Mar',
    linkedPlantSlug: 'marigold-genda',
  },
  {
    name: 'Sunflower (Dwarf Teddy Bear) Seeds',
    scientificName: 'Helianthus annuus',
    slug: 'seeds-sunflower-dwarf',
    description: '"Teddy Bear" is a compact dwarf sunflower (40–50 cm) perfect for pots — fluffy, golden double flowers that are irresistibly charming. Ready in just 60 days from seed and perfect for any balcony.',
    price: 39, comparePrice: 59, stock: 350,
    thumbnailUrl: P(1366630), images: [P(1366630)],
    categories: ['flowering', 'outdoor'],
    difficulty: 'beginner', tags: ['dwarf-variety', 'pot-friendly', 'double-flower', 'kids-favourite'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '5–8 days', sowingDepth: '1 cm', sowingMethod: 'Direct sow (1 seed per pot)',
    harvestDays: '55–65 days', seedsPerPacket: 15, sowingSeason: 'Jan–Mar, Aug–Sep',
    linkedPlantSlug: 'sunflower',
  },
  {
    name: 'Petunia (Mixed) Seeds',
    scientificName: 'Petunia × hybrida',
    slug: 'seeds-petunia-mixed',
    description: 'Mixed petunia seeds in lavender, pink, red, white, and bi-colour. Petunias are the best winter hanging basket plant for Indian balconies — cascading, fragrant, and blooming for 4+ months.',
    price: 49, comparePrice: 75, stock: 300,
    thumbnailUrl: P(2293374), images: [P(2293374)],
    categories: ['flowering', 'outdoor'],
    difficulty: 'intermediate', tags: ['hanging-basket', 'winter-bloomer', 'fragrant', 'cascading'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '7–12 days', sowingDepth: 'Surface sow (needs light to germinate)', sowingMethod: 'Seedling tray — press onto moist soil surface, do not cover',
    harvestDays: '60–80 days to first bloom', seedsPerPacket: 30, sowingSeason: 'Aug–Oct',
    linkedPlantSlug: 'petunia',
  },
  {
    name: 'Portulaca (Moss Rose Mix) Seeds',
    scientificName: 'Portulaca grandiflora',
    slug: 'seeds-portulaca',
    description: 'The most drought-tolerant flowering seeds you can sow. Portulaca thrives in Indian heat, blooms in vivid pink, red, orange, and yellow, and asks for water only every 4–5 days. Perfect for forgetful gardeners.',
    price: 29, comparePrice: 45, stock: 500,
    thumbnailUrl: P(2293374), images: [P(2293374)],
    categories: ['flowering', 'succulent', 'outdoor'],
    difficulty: 'beginner', tags: ['drought-tolerant', 'summer-bloomer', 'mixed-colours', 'direct-sow'],
    isBestseller: true, isNewArrival: false,
    germinationDays: '7–10 days', sowingDepth: 'Surface sow (press, do not bury)', sowingMethod: 'Sprinkle on surface, press gently, do not cover — needs light',
    harvestDays: '40–50 days to bloom', seedsPerPacket: 200, sowingSeason: 'Feb–May',
    linkedPlantSlug: 'portulaca-moss-rose',
  },
  {
    name: 'Vinca (Mixed Colours) Seeds',
    scientificName: 'Catharanthus roseus',
    slug: 'seeds-vinca',
    description: 'Vinca seeds in a rainbow mix — pink, red, white, magenta, and bi-colour. The single best flower for blazing Indian summers — blooms continuously in heat that kills other flowers.',
    price: 35, comparePrice: 55, stock: 400,
    thumbnailUrl: P(2293374), images: [P(2293374)],
    categories: ['flowering', 'outdoor'],
    difficulty: 'beginner', tags: ['heat-tolerant', 'summer-bloomer', 'mixed-colours', 'low-maintenance'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '7–14 days', sowingDepth: '0.3 cm', sowingMethod: 'Seedling tray (dark germinator — cover lightly)',
    harvestDays: '50–70 days to bloom', seedsPerPacket: 30, sowingSeason: 'Feb–Apr, Aug–Oct',
    linkedPlantSlug: 'vinca-periwinkle',
  },
  {
    name: 'Dahlia (Dwarf Mix) Seeds',
    scientificName: 'Dahlia pinnata',
    slug: 'seeds-dahlia-dwarf',
    description: 'Dwarf dahlia seeds that produce compact plants (30–40 cm) perfect for pots and window boxes. Spectacular double and semi-double flowers in red, orange, pink, yellow, and white — a Diwali season showstopper.',
    price: 59, comparePrice: 89, stock: 200,
    thumbnailUrl: P(931177), images: [P(931177)],
    categories: ['flowering', 'outdoor'],
    difficulty: 'intermediate', tags: ['dwarf-variety', 'pot-friendly', 'winter-bloomer', 'festival-flower'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '7–14 days', sowingDepth: '0.5 cm', sowingMethod: 'Seedling tray, then transplant',
    harvestDays: '90–120 days to bloom', seedsPerPacket: 15, sowingSeason: 'Jul–Aug',
    linkedPlantSlug: 'dahlia',
  },
  {
    name: 'Gerbera (Mixed) Seeds',
    scientificName: 'Gerbera jamesonii',
    slug: 'seeds-gerbera',
    description: 'Large, cheerful daisy-like flowers in vivid red, orange, yellow, and pink. Grow from seed for winter blooms. Each flower lasts 2+ weeks on the plant — great as cut flowers too.',
    price: 69, comparePrice: 99, stock: 150,
    thumbnailUrl: P(2293374), images: [P(2293374)],
    categories: ['flowering', 'outdoor'],
    difficulty: 'intermediate', tags: ['cut-flower', 'winter-bloomer', 'mixed-colours', 'long-lasting'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '10–15 days', sowingDepth: '0.3 cm', sowingMethod: 'Seedling tray (seeds need light — barely cover)',
    harvestDays: '120–150 days to bloom', seedsPerPacket: 15, sowingSeason: 'Aug–Sep',
    linkedPlantSlug: 'gerbera-daisy',
  },

  // ─── FRUITS ──────────────────────────────────────────────────────────────
  {
    name: 'Strawberry (Elan F1) Seeds',
    scientificName: 'Fragaria × ananassa',
    slug: 'seeds-strawberry',
    description: 'Grow sweet, juicy strawberries from seed on your winter balcony. The Elan F1 variety produces early, firm berries perfect for container growing. Start in August–September for January–February harvest.',
    price: 99, comparePrice: 149, stock: 150,
    thumbnailUrl: P(1435904), images: [P(1435904)],
    categories: ['fruit', 'outdoor'],
    difficulty: 'intermediate', tags: ['winter-fruit', 'pot-friendly', 'hanging-basket', 'kids-favourite'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '14–21 days', sowingDepth: 'Surface sow', sowingMethod: 'Press onto moist soil surface. Chill seeds in fridge for 2 weeks before sowing for better germination.',
    harvestDays: '120–150 days', seedsPerPacket: 20, sowingSeason: 'Aug–Sep',
    linkedPlantSlug: 'strawberry',
  },
  {
    name: 'Watermelon (Sugar Baby) Seeds',
    scientificName: 'Citrullus lanatus',
    slug: 'seeds-watermelon-sugar-baby',
    description: '"Sugar Baby" is a compact, early-maturing watermelon — fruits weigh 2–3 kg each, ideal for terrace gardens. Needs a large 30L grow bag and full sun, but rewards with the sweetest, crunchiest fruits possible.',
    price: 49, comparePrice: 75, stock: 200,
    thumbnailUrl: P(2286776), images: [P(2286776)],
    categories: ['fruit', 'outdoor'],
    difficulty: 'intermediate', tags: ['compact-variety', 'terrace-garden', 'summer-fruit', 'early-maturing'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '4–7 days', sowingDepth: '2 cm', sowingMethod: 'Direct sow (2 seeds per hole, thin to 1)',
    harvestDays: '75–85 days', seedsPerPacket: 15, sowingSeason: 'Feb–Mar',
    linkedPlantSlug: null,
  },

  // ─── INDOOR / MICROGREENS ─────────────────────────────────────────────────
  {
    name: 'Microgreens Mix Seeds',
    scientificName: 'Various species',
    slug: 'seeds-microgreens-mix',
    description: 'A curated mix of 8 fast-growing microgreen varieties — sunflower, radish, mustard, fenugreek, peas, coriander, amaranth, and basil. Grow in a kitchen tray, ready to harvest in 7–14 days. Nutrient-dense and delicious.',
    price: 79, comparePrice: 119, stock: 400,
    thumbnailUrl: P(4033471), images: [P(4033471)],
    categories: ['indoor', 'herb', 'vegetable'],
    difficulty: 'beginner', tags: ['microgreens', 'kitchen-counter', 'ultra-fast', 'superfood', 'mixed'],
    isBestseller: true, isNewArrival: true,
    germinationDays: '2–5 days', sowingDepth: 'Surface sow densely', sowingMethod: 'Spread densely on moist coco peat, mist and cover for 3 days',
    harvestDays: '7–14 days', seedsPerPacket: 0, sowingSeason: 'All year indoors',
    linkedPlantSlug: 'microgreens-starter',
  },
  {
    name: 'Wheatgrass Seeds (Gehun)',
    scientificName: 'Triticum aestivum',
    slug: 'seeds-wheatgrass',
    description: 'Premium, chemical-free wheat seeds for growing wheatgrass at home. Ready to juice in 8–10 days. One tray gives 60–90 ml of nutrient-packed wheatgrass juice — worth ₹60+ at health stores. Grow it for peanuts.',
    price: 39, comparePrice: 59, stock: 500,
    thumbnailUrl: P(4033471), images: [P(4033471)],
    categories: ['indoor', 'herb'],
    difficulty: 'beginner', tags: ['wheatgrass', 'juicing', 'superfood', 'kitchen-counter', 'fast-harvest'],
    isBestseller: false, isNewArrival: false,
    germinationDays: '1–2 days', sowingDepth: 'Surface (soak seeds overnight first)', sowingMethod: 'Spread soaked seeds on moist coco peat, cover for 2 days',
    harvestDays: '8–10 days', seedsPerPacket: 0, sowingSeason: 'All year indoors',
    linkedPlantSlug: 'wheatgrass',
  },
  {
    name: 'Sunflower Microgreen Seeds',
    scientificName: 'Helianthus annuus',
    slug: 'seeds-sunflower-microgreens',
    description: 'Sunflower microgreens are the tastiest and most nutritious microgreens you can grow — with a nutty, crunchy texture. Ready in 10–12 days, eaten as salad greens, garnishes, or straight from the tray.',
    price: 49, comparePrice: 69, stock: 300,
    thumbnailUrl: P(1366630), images: [P(1366630)],
    categories: ['indoor', 'vegetable'],
    difficulty: 'beginner', tags: ['microgreens', 'kitchen-counter', 'nutty-flavour', 'high-protein'],
    isBestseller: false, isNewArrival: true,
    germinationDays: '2–3 days', sowingDepth: 'Soak 8 hrs, spread on coco peat surface', sowingMethod: 'Soak seeds 8 hrs, drain, spread on moist coco peat, cover 3 days',
    harvestDays: '10–12 days', seedsPerPacket: 0, sowingSeason: 'All year indoors',
    linkedPlantSlug: null,
  },
]

async function main() {
  console.log(`🌱 Seeding ${seeds.length} seed products...`)
  let added = 0, skipped = 0

  for (const seed of seeds) {
    const exists = await prisma.seed.findUnique({ where: { slug: seed.slug } })
    if (exists) { console.log(`  ⏭️  Already exists: ${seed.name}`); skipped++; continue }
    await prisma.seed.create({ data: seed as never })
    console.log(`  ✅ ${seed.name}`)
    added++
  }

  console.log(`\n✅ Done — ${added} seeds added, ${skipped} skipped`)
  const total = await prisma.seed.count({ where: { isActive: true } })
  console.log(`📊 Total seeds in catalog: ${total}`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
