import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.info('🌱 Seeding database...')

  const adminPassword = await bcrypt.hash('admin123', 12)
  await prisma.user.upsert({
    where: { email: 'admin@verdura.in' },
    update: {},
    create: { name: 'Verdura Admin', email: 'admin@verdura.in', passwordHash: adminPassword, role: 'admin' },
  })

  const plants = [
    // ─── INDOOR PLANTS ───────────────────────────────────────────────────────
    {
      name: 'Monstera', scientificName: 'Monstera deliciosa', slug: 'monstera-deliciosa',
      description: 'The iconic split-leaf plant, beloved across Indian homes for its dramatic tropical foliage and effortless indoor charm.',
      price: 349, comparePrice: 499, stock: 50,
      thumbnailUrl: '/images/plants/monstera.jpg', images: ['/images/plants/monstera.jpg'],
      categories: ['indoor', 'tropical'], difficulty: 'beginner', tags: ['low-maintenance', 'pet-friendly'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 7 days', careSunlight: 'Bright indirect', careHumidity: '40–60%', careTemperature: '18–30°C',
      wateringIntervalDays: 7, fertiliserIntervalDays: 14, pruningIntervalDays: 60, repottingIntervalMonths: 18,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water thoroughly when the top 2–3 cm of soil feels dry. Ensure good drainage. Reduce to every 10–12 days in winter.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Bright indirect light — north or east-facing window is ideal. Avoid harsh afternoon sun that scorches leaves.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed every 2 weeks in summer with balanced liquid fertiliser at half strength. Skip in winter.', order: 3 },
        { title: 'Repotting', icon: '🪴', body: 'Repot every 1–2 years when roots circle the base. Move up one pot size only — too large causes waterlogging.', order: 4 },
        { title: 'Common problems', icon: '🐛', body: 'Yellow leaves = overwatering. Brown tips = low humidity or direct sun. Leggy growth = insufficient light.', order: 5 },
      ]},
    },
    {
      name: 'Snake plant', scientificName: 'Sansevieria trifasciata', slug: 'snake-plant',
      description: 'India\'s most forgiving houseplant — tolerates neglect, releases oxygen at night, and thrives in any corner.',
      price: 199, comparePrice: 299, stock: 80,
      thumbnailUrl: '/images/plants/snake-plant.jpg', images: ['/images/plants/snake-plant.jpg'],
      categories: ['indoor', 'air_purifying'], difficulty: 'beginner', tags: ['low-light', 'air-purifier', 'night-oxygen'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 14 days', careSunlight: 'Low to bright indirect', careHumidity: 'Any', careTemperature: '15–35°C',
      wateringIntervalDays: 14, fertiliserIntervalDays: 30, pruningIntervalDays: 90,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Let soil dry completely between waterings. In summer once a week, in winter once a month. Root rot from overwatering is the #1 killer.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Extremely tolerant — survives in dim corners but grows fastest in indirect bright light. Avoid prolonged harsh sun.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Fertilise once each in April and July with diluted fertiliser. Over-feeding causes pale, weak growth.', order: 3 },
        { title: 'Indian summer tip', icon: '🌡️', body: 'Move away from south-facing windows during peak Indian summer (April–June). Hot glass can scorch the tips.', order: 4 },
      ]},
    },
    {
      name: 'Money plant', scientificName: 'Epipremnum aureum', slug: 'money-plant',
      description: 'The most popular Indian houseplant — grows in water or soil, believed to bring prosperity and purify indoor air.',
      price: 99, comparePrice: 149, stock: 150,
      thumbnailUrl: '/images/plants/money-plant.jpg', images: ['/images/plants/money-plant.jpg'],
      categories: ['indoor', 'air_purifying'], difficulty: 'beginner', tags: ['low-light', 'air-purifier', 'lucky', 'fast-growing'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 7 days', careSunlight: 'Low to moderate indirect', careHumidity: '40–70%', careTemperature: '15–30°C',
      wateringIntervalDays: 7, fertiliserIntervalDays: 21, pruningIntervalDays: 30,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'In soil: water when top inch is dry. In water: change water every 7–10 days and add a few drops of liquid fertiliser monthly.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Thrives anywhere from dim rooms to bright indirect light. Direct sun bleaches the golden variegation.', order: 2 },
        { title: 'Propagation', icon: '🌿', body: 'Snip a 15 cm stem below a node and place in water — roots appear in 1–2 weeks. One plant can fill your whole home!', order: 3 },
        { title: 'Pruning', icon: '✂️', body: 'Trim leggy vines to encourage bushy growth. Pinch tips monthly for fuller, denser foliage.', order: 4 },
      ]},
    },
    {
      name: 'Areca palm', scientificName: 'Dypsis lutescens', slug: 'areca-palm',
      description: 'India\'s favourite living room palm — removes indoor toxins and adds a lush tropical feel to any space.',
      price: 549, comparePrice: 749, stock: 30,
      thumbnailUrl: '/images/plants/areca-palm.jpg', images: ['/images/plants/areca-palm.jpg'],
      categories: ['indoor', 'tropical', 'air_purifying'], difficulty: 'intermediate', tags: ['air-purifier', 'living-room', 'pet-safe'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 5 days', careSunlight: 'Bright indirect', careHumidity: '50–70%', careTemperature: '16–32°C',
      wateringIntervalDays: 5, fertiliserIntervalDays: 14, repottingIntervalMonths: 24,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Keep soil evenly moist but never waterlogged. Water more frequently in Indian summers — daily misting of fronds helps.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Bright indirect light is best. Can tolerate partial shade. Rotate quarterly for even growth.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed with palm-specific or balanced NPK fertiliser every 2 weeks in growing season (March–September).', order: 3 },
        { title: 'Humidity', icon: '💦', body: 'Group with other plants or place on a pebble tray with water to maintain humidity. Brown leaf tips indicate dry air.', order: 4 },
        { title: 'Common problems', icon: '🐛', body: 'Spider mites in dry weather — mist frequently. Yellow fronds usually mean overwatering or poor drainage.', order: 5 },
      ]},
    },
    {
      name: 'Aglaonema', scientificName: 'Aglaonema commutatum', slug: 'aglaonema',
      description: 'Strikingly beautiful red and green patterned leaves — one of the hardiest and most colourful plants for Indian interiors.',
      price: 299, comparePrice: 399, stock: 45,
      thumbnailUrl: '/images/plants/aglaonema.jpg', images: ['/images/plants/aglaonema.jpg'],
      categories: ['indoor', 'air_purifying'], difficulty: 'beginner', tags: ['colourful', 'low-light', 'air-purifier'],
      isBestseller: false, isNewArrival: true,
      careWatering: 'Every 7 days', careSunlight: 'Low to medium indirect', careHumidity: '40–60%', careTemperature: '18–30°C',
      wateringIntervalDays: 7, fertiliserIntervalDays: 21, repottingIntervalMonths: 24,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water when the top 2 cm of soil is dry. Reduce to every 10 days in winter. Avoid waterlogging — use well-draining mix.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Tolerates low light but red varieties need more light to maintain their vivid colour. Never direct sun.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed monthly in summer. Excess fertiliser causes salt build-up — flush soil with clean water every 2–3 months.', order: 3 },
        { title: 'Toxicity', icon: '⚠️', body: 'Mildly toxic to pets and children. Wear gloves when pruning as sap can irritate skin.', order: 4 },
      ]},
    },
    {
      name: 'ZZ plant', scientificName: 'Zamioculcas zamiifolia', slug: 'zz-plant',
      description: 'The unkillable office plant — stores water in its roots, thrives in low light and long stretches of neglect.',
      price: 349, comparePrice: 449, stock: 35,
      thumbnailUrl: '/images/plants/zz-plant.jpg', images: ['/images/plants/zz-plant.jpg'],
      categories: ['indoor'], difficulty: 'beginner', tags: ['drought-tolerant', 'low-light', 'office-friendly'],
      isBestseller: false, isNewArrival: false,
      careWatering: 'Every 14 days', careSunlight: 'Low to bright indirect', careHumidity: 'Any', careTemperature: '15–35°C',
      wateringIntervalDays: 14, fertiliserIntervalDays: 30, repottingIntervalMonths: 24,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Allow soil to dry fully before watering. Can go 3–4 weeks without water in winter. Overwatering is the only way to kill it.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Survives in dark corridors. Grows faster near a window. Direct sunlight yellows the leaves.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed once in spring and once in summer — that\'s it. Over-fertilising causes brown leaf tips.', order: 3 },
        { title: 'Toxicity', icon: '⚠️', body: 'All parts are toxic if ingested. Keep away from pets and children. Sap causes skin irritation — wash hands after handling.', order: 4 },
      ]},
    },
    {
      name: 'Rubber plant', scientificName: 'Ficus elastica', slug: 'rubber-plant',
      description: 'Bold, glossy burgundy leaves — a statement indoor tree that purifies air and grows tall over the years.',
      price: 449, comparePrice: 599, stock: 25,
      thumbnailUrl: '/images/plants/rubber-plant.jpg', images: ['/images/plants/rubber-plant.jpg'],
      categories: ['indoor', 'air_purifying'], difficulty: 'intermediate', tags: ['statement-plant', 'air-purifier', 'fast-growing'],
      isBestseller: false, isNewArrival: true,
      careWatering: 'Every 7 days', careSunlight: 'Bright indirect to some direct', careHumidity: '40–60%', careTemperature: '15–30°C',
      wateringIntervalDays: 7, fertiliserIntervalDays: 14, pruningIntervalDays: 60, repottingIntervalMonths: 18,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water when top 2 cm is dry. Wipe large leaves with a damp cloth monthly to remove dust that blocks light absorption.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Needs bright light to maintain dark colour. Acclimatise to morning sun for richest burgundy hue.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed every 2 weeks in summer. Rapid grower — can add 30–60 cm per year in good conditions.', order: 3 },
        { title: 'Sticky sap', icon: '⚠️', body: 'White sap from cut stems stains fabric and irritates skin. Use gloves when pruning and place newspaper beneath.', order: 4 },
      ]},
    },
    {
      name: 'Peace lily', scientificName: 'Spathiphyllum wallisii', slug: 'peace-lily',
      description: 'Elegant white flowers and powerful air-purifying properties — perfect for bedrooms and living rooms.',
      price: 279, comparePrice: 379, stock: 40,
      thumbnailUrl: '/images/plants/peace-lily.jpg', images: ['/images/plants/peace-lily.jpg'],
      categories: ['indoor', 'air_purifying', 'flowering'], difficulty: 'intermediate', tags: ['air-purifier', 'flowering', 'bedroom'],
      isBestseller: false, isNewArrival: true,
      careWatering: 'Every 5 days', careSunlight: 'Low to medium indirect', careHumidity: '50%+', careTemperature: '18–27°C',
      wateringIntervalDays: 5, fertiliserIntervalDays: 30, repottingIntervalMonths: 24,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Keep soil consistently moist. Peace lilies droop when thirsty — use this as a watering cue. Mist leaves weekly.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Thrives in low light. Direct sun causes brown crispy edges. Even office fluorescent light is sufficient.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed monthly in the growing season. Yellow leaves often signal a nutrient deficiency.', order: 3 },
        { title: 'Toxicity', icon: '⚠️', body: 'Mildly toxic to cats, dogs, and children if ingested. Keep away from pets.', order: 4 },
      ]},
    },

    // ─── OUTDOOR PLANTS ──────────────────────────────────────────────────────
    {
      name: 'Hibiscus', scientificName: 'Hibiscus rosa-sinensis', slug: 'hibiscus',
      description: 'India\'s pride — vibrant blooms in red, pink, yellow and white. Attracts butterflies and hummingbirds. Also used in traditional hair oil.',
      price: 199, comparePrice: 269, stock: 60,
      thumbnailUrl: '/images/plants/hibiscus.jpg', images: ['/images/plants/hibiscus.jpg'],
      categories: ['outdoor', 'flowering'], difficulty: 'beginner', tags: ['flowering', 'fast-growing', 'medicinal', 'attracts-butterflies'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Full sun (5–6 hrs)', careHumidity: '50–70%', careTemperature: '20–35°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14, pruningIntervalDays: 30, repottingIntervalMonths: 12,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water daily in peak summer. Keep soil moist but not waterlogged. Reduce in winter — every 3–4 days is sufficient.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Needs 5–6 hours of direct sun daily. South-facing balcony or terrace is ideal. Fewer flowers in shade.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed with high-potassium fertiliser (0-10-10 or banana peel water) every 2 weeks during flowering season for more blooms.', order: 3 },
        { title: 'Pruning', icon: '✂️', body: 'Prune up to 1/3 of the plant after each blooming cycle. Cutting just above a node triggers new flowering shoots.', order: 4 },
        { title: 'Traditional use', icon: '🌺', body: 'Red hibiscus flowers are used in hair oil and as natural conditioner. Soak petals overnight and use the water for hair.', order: 5 },
      ]},
    },
    {
      name: 'Bougainvillea', scientificName: 'Bougainvillea spectabilis', slug: 'bougainvillea',
      description: 'The drought-hardy, brilliant flowering climber — iconic on Indian walls, gates and terraces in blazing pink, orange and purple.',
      price: 249, comparePrice: 349, stock: 40,
      thumbnailUrl: '/images/plants/bougainvillea.jpg', images: ['/images/plants/bougainvillea.jpg'],
      categories: ['outdoor', 'flowering'], difficulty: 'beginner', tags: ['drought-tolerant', 'flowering', 'climber', 'fast-growing'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 3 days', careSunlight: 'Full sun (6+ hrs)', careHumidity: '40–60%', careTemperature: '20–40°C',
      wateringIntervalDays: 3, fertiliserIntervalDays: 21, pruningIntervalDays: 30,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Drought tolerant once established. Water deeply, then let soil dry — stress actually triggers more flowering. Avoid waterlogging.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Needs at least 6 hours of full sun. The more sun, the more vibrant the bracts. Will not flower in shade.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Use bloom-booster (high phosphorus) fertiliser every 3 weeks during flowering. Avoid high nitrogen — it promotes leaves, not flowers.', order: 3 },
        { title: 'Pruning', icon: '✂️', body: 'Hard prune after each flush of flowers. Shape and remove dead wood. New shoots from cut tips will bloom within 6–8 weeks.', order: 4 },
        { title: 'Thorns', icon: '⚠️', body: 'Bougainvillea has sharp thorns — wear thick gloves when pruning. Keep away from children\'s play areas.', order: 5 },
      ]},
    },
    {
      name: 'Mogra (Arabian jasmine)', scientificName: 'Jasminum sambac', slug: 'mogra-jasmine',
      description: 'The fragrance of Indian summers — intensely perfumed white flowers used in garlands, hair and religious offerings.',
      price: 179, comparePrice: 239, stock: 55,
      thumbnailUrl: '/images/plants/mogra.jpg', images: ['/images/plants/mogra.jpg'],
      categories: ['outdoor', 'flowering'], difficulty: 'beginner', tags: ['fragrant', 'flowering', 'religious', 'attracts-bees'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Full to partial sun (4–6 hrs)', careHumidity: '50–70%', careTemperature: '20–35°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14, pruningIntervalDays: 21,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water in the morning every 1–2 days in summer. Keep moist but not soggy. Mulch around the base to retain moisture.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Minimum 4 hours of sun for flowering. Best near south or west-facing walls. Partial shade slows bloom production.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed with DAP or balanced NPK monthly. Apply banana peel compost for more fragrant flowers. Bone meal boosts blooming.', order: 3 },
        { title: 'Pruning', icon: '✂️', body: 'After each flowering flush, prune 10–15 cm to encourage new shoots. Shape to keep bushy.', order: 4 },
        { title: 'Harvesting', icon: '🌸', body: 'Harvest flowers in the morning before they fully open for maximum fragrance. Flowers last 2–3 days in a cool container.', order: 5 },
      ]},
    },
    {
      name: 'Croton', scientificName: 'Codiaeum variegatum', slug: 'croton',
      description: 'Explosively colourful foliage in yellow, red, orange and green — the most vivid outdoor/balcony plant for Indian gardens.',
      price: 219, comparePrice: 299, stock: 45,
      thumbnailUrl: '/images/plants/croton.jpg', images: ['/images/plants/croton.jpg'],
      categories: ['outdoor'], difficulty: 'intermediate', tags: ['colourful', 'balcony', 'tropical'],
      isBestseller: false, isNewArrival: true,
      careWatering: 'Every 3 days', careSunlight: 'Bright direct to indirect', careHumidity: '50–70%', careTemperature: '18–35°C',
      wateringIntervalDays: 3, fertiliserIntervalDays: 14, pruningIntervalDays: 45,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Keep soil consistently moist. Croton drops leaves when stressed — regular watering prevents this.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Bright light intensifies leaf colour. Morning direct sun is ideal. Low light makes leaves lose their vivid hues.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed every 2 weeks in summer with balanced fertiliser. Reduce to monthly in winter.', order: 3 },
        { title: 'Leaf drop', icon: '🍂', body: 'Drooping and leaf drop is caused by temperature shock, moving the plant, or inconsistent watering. Keep in one stable spot.', order: 4 },
      ]},
    },

    // ─── VEGETABLES ──────────────────────────────────────────────────────────
    {
      name: 'Tomato (Desi)', scientificName: 'Solanum lycopersicum', slug: 'tomato-desi',
      description: 'The foundation of every Indian kitchen — grow fresh, pesticide-free desi tomatoes on your terrace or balcony year-round.',
      price: 79, comparePrice: 99, stock: 100,
      thumbnailUrl: '/images/plants/tomato.jpg', images: ['/images/plants/tomato.jpg'],
      categories: ['outdoor', 'vegetable'], difficulty: 'beginner', tags: ['edible', 'fast-growing', 'terrace-garden', 'kitchen-garden'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every day', careSunlight: 'Full sun (6–8 hrs)', careHumidity: '40–70%', careTemperature: '20–30°C',
      wateringIntervalDays: 1, fertiliserIntervalDays: 7, pruningIntervalDays: 7,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water daily in summer — tomatoes are thirsty! Inconsistent watering causes blossom end rot and cracking. Water at the base, not leaves.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Needs 6–8 hours of full sun. Terrace gardens work brilliantly. South or west-facing balcony is ideal.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'After flowering starts, feed with high-potassium fertiliser (like tomato fertiliser) weekly. Jeevamrut or compost tea works excellently.', order: 3 },
        { title: 'Staking', icon: '🪵', body: 'Stake with a bamboo stick or rope once plants reach 30 cm. Tie loosely every 20 cm as the plant grows.', order: 4 },
        { title: 'Pruning suckers', icon: '✂️', body: 'Remove suckers (side shoots in leaf axils) weekly. This redirects energy to fruit production and keeps plants manageable.', order: 5 },
        { title: 'Harvesting', icon: '🍅', body: 'Harvest when fully red and firm. First fruits appear 60–80 days after transplanting. Pick regularly to encourage continuous production.', order: 6 },
      ]},
    },
    {
      name: 'Bhindi (Okra)', scientificName: 'Abelmoschus esculentus', slug: 'bhindi-okra',
      description: 'The easiest vegetable for Indian home gardens — grows rapidly in heat, produces abundantly and needs minimal care.',
      price: 59, comparePrice: 79, stock: 120,
      thumbnailUrl: '/images/plants/bhindi.jpg', images: ['/images/plants/bhindi.jpg'],
      categories: ['outdoor', 'vegetable'], difficulty: 'beginner', tags: ['edible', 'fast-growing', 'summer-crop', 'heat-tolerant'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Full sun (6+ hrs)', careHumidity: '40–70%', careTemperature: '25–40°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14, pruningIntervalDays: 14,
      careGuide: { create: [
        { title: 'Sowing', icon: '🌱', body: 'Sow seeds directly in pots (30 cm+ deep) or ground. Soak seeds overnight before sowing for better germination. Seeds germinate in 5–7 days.', order: 1 },
        { title: 'Watering', icon: '💧', body: 'Water every 2 days in summer — bhindi loves heat and moisture. Water at the base to prevent fungal issues.', order: 2 },
        { title: 'Sunlight', icon: '☀️', body: 'Thrives in Indian summer heat. Minimum 6 hours full sun. Perfect for terrace gardens during April–September.', order: 3 },
        { title: 'Fertilising', icon: '🧪', body: 'Apply compost or balanced fertiliser at planting. Feed with NPK 10-10-10 every 2 weeks. Potassium boosts pod quality.', order: 4 },
        { title: 'Harvesting', icon: '🫛', body: 'Pick pods when 7–10 cm long and tender — about 50–65 days from sowing. Harvest every 2–3 days or pods become tough and stringy.', order: 5 },
      ]},
    },
    {
      name: 'Green chilli', scientificName: 'Capsicum annuum', slug: 'green-chilli',
      description: 'No Indian kitchen is complete without fresh green chillies. Compact plant, heavy producer, ideal for pots and balconies.',
      price: 69, comparePrice: 89, stock: 110,
      thumbnailUrl: '/images/plants/green-chilli.jpg', images: ['/images/plants/green-chilli.jpg'],
      categories: ['outdoor', 'vegetable', 'herb'], difficulty: 'beginner', tags: ['edible', 'spicy', 'pot-friendly', 'kitchen-garden'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Full sun (5–6 hrs)', careHumidity: '40–70%', careTemperature: '20–35°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14, pruningIntervalDays: 30,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water every 2 days in summer. Allow top inch to dry before rewatering. Overwatering causes root rot and yellowing.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Needs 5–6 hours of direct sun for good production. Balcony or terrace with southern exposure works perfectly.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Once flowering begins, switch to a potassium-rich fertiliser (wood ash tea or 0-0-50). Avoid excess nitrogen — it delays fruiting.', order: 3 },
        { title: 'Harvesting', icon: '🌶️', body: 'Green chillies are ready 70–85 days from transplanting. Pick regularly to encourage more fruits. Leave some to turn red for ripe chilli powder.', order: 4 },
        { title: 'Pests', icon: '🐛', body: 'Watch for aphids on new growth. Spray neem oil solution (5ml neem + 1L water + a drop of soap) every 2 weeks as prevention.', order: 5 },
      ]},
    },
    {
      name: 'Brinjal (Eggplant)', scientificName: 'Solanum melongena', slug: 'brinjal-eggplant',
      description: 'The king of Indian vegetables — grows prolifically in heat, producing large purple fruits from July to November.',
      price: 79, comparePrice: 99, stock: 80,
      thumbnailUrl: '/images/plants/brinjal.jpg', images: ['/images/plants/brinjal.jpg'],
      categories: ['outdoor', 'vegetable'], difficulty: 'beginner', tags: ['edible', 'heat-tolerant', 'heavy-producer', 'kitchen-garden'],
      isBestseller: false, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Full sun (6–8 hrs)', careHumidity: '50–70%', careTemperature: '22–35°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14, pruningIntervalDays: 30,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Keep soil consistently moist. Water every 1–2 days in summer. Mulch soil to retain moisture and reduce watering frequency.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Full sun is essential. At least 6–8 hours daily. Thrives on terraces and in open gardens during Indian monsoon and post-monsoon.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Side-dress with compost or balanced NPK every 2 weeks. Once fruiting starts, increase potassium for better fruit set.', order: 3 },
        { title: 'Staking', icon: '🪵', body: 'Stake plants when 40 cm tall. Fruit weight can topple unsupported plants. Bamboo stakes work well.', order: 4 },
        { title: 'Harvesting', icon: '🍆', body: 'Harvest when fruits are glossy, firm, and full-sized — 70–85 days from transplanting. Over-ripe fruits become seedy and bitter.', order: 5 },
      ]},
    },
    {
      name: 'Spinach (Palak)', scientificName: 'Spinacia oleracea', slug: 'spinach-palak',
      description: 'Nutrient-dense leafy green ready in just 30 days — perfect for small balcony pots and kitchen window boxes throughout winter.',
      price: 49, comparePrice: 69, stock: 150,
      thumbnailUrl: '/images/plants/palak.jpg', images: ['/images/plants/palak.jpg'],
      categories: ['outdoor', 'vegetable', 'herb'], difficulty: 'beginner', tags: ['edible', 'fast-growing', 'winter-crop', 'nutritious'],
      isBestseller: false, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Partial to full sun (4–6 hrs)', careHumidity: '40–70%', careTemperature: '10–25°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14,
      careGuide: { create: [
        { title: 'Season', icon: '📅', body: 'Best grown October–March in most of India. Avoid summer — spinach bolts quickly in heat. Ideal in the cool months.', order: 1 },
        { title: 'Sowing', icon: '🌱', body: 'Sow seeds directly 1 cm deep, 5 cm apart. Keep moist until germination (5–7 days). Thin to 10 cm apart once seedlings are 5 cm tall.', order: 2 },
        { title: 'Watering', icon: '💧', body: 'Keep soil consistently moist. Water every 2 days. Avoid overwatering in cool weather — reduce frequency as temperatures drop.', order: 3 },
        { title: 'Fertilising', icon: '🧪', body: 'Nitrogen-rich fertiliser (like vermicompost or urea) every 2 weeks promotes lush leaf growth.', order: 4 },
        { title: 'Harvesting', icon: '🥬', body: 'Cut outer leaves when 10–15 cm tall — leaves grow back. Full harvest at 40–50 days. Cut 2 cm above soil for continuous regrowth.', order: 5 },
      ]},
    },
    {
      name: 'Methi (Fenugreek)', scientificName: 'Trigonella foenum-graecum', slug: 'methi-fenugreek',
      description: 'Aromatic, nutritious and ready in 3 weeks — the ultimate quick-win kitchen garden plant for Indian homes.',
      price: 39, comparePrice: 59, stock: 200,
      thumbnailUrl: '/images/plants/methi.jpg', images: ['/images/plants/methi.jpg'],
      categories: ['outdoor', 'vegetable', 'herb'], difficulty: 'beginner', tags: ['edible', 'super-fast', 'medicinal', 'kitchen-garden'],
      isBestseller: false, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Partial to full sun (4–5 hrs)', careHumidity: '40–60%', careTemperature: '10–28°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14,
      careGuide: { create: [
        { title: 'Sowing', icon: '🌱', body: 'Sow densely (like grass seed) directly in any container. No thinning needed for microgreens. Germinates in just 2–3 days.', order: 1 },
        { title: 'Watering', icon: '💧', body: 'Keep soil moist throughout. A spray bottle works well for small pots. Avoid overwatering — good drainage essential.', order: 2 },
        { title: 'Harvesting', icon: '🌿', body: 'Cut leaves when 10–15 cm tall (about 20–25 days). Cut 2 cm above soil — they will regrow 2–3 times. Seeds can be dried for use as the spice.', order: 3 },
        { title: 'Medicinal use', icon: '💊', body: 'Methi leaves reduce blood sugar, improve digestion and are used in hair care. Seeds soaked overnight can be consumed for health benefits.', order: 4 },
      ]},
    },
    {
      name: 'Bitter gourd (Karela)', scientificName: 'Momordica charantia', slug: 'bitter-gourd-karela',
      description: 'India\'s most medicinal vegetable — climbs vigorously on a trellis and produces abundantly in the monsoon season.',
      price: 69, comparePrice: 89, stock: 70,
      thumbnailUrl: '/images/plants/karela.jpg', images: ['/images/plants/karela.jpg'],
      categories: ['outdoor', 'vegetable'], difficulty: 'intermediate', tags: ['edible', 'medicinal', 'climber', 'diabetic-friendly'],
      isBestseller: false, isNewArrival: false,
      careWatering: 'Every day', careSunlight: 'Full sun (6–8 hrs)', careHumidity: '60–80%', careTemperature: '25–40°C',
      wateringIntervalDays: 1, fertiliserIntervalDays: 14, pruningIntervalDays: 14,
      careGuide: { create: [
        { title: 'Trellis', icon: '🪵', body: 'Set up a trellis, bamboo frame or railing before planting. Karela climbs 2–4 metres — it needs strong support for heavy fruit.', order: 1 },
        { title: 'Sowing', icon: '🌱', body: 'Sow after last winter frost (February in South India, April in North India). Soak seeds 24 hours before sowing for better germination.', order: 2 },
        { title: 'Watering', icon: '💧', body: 'Needs daily watering in summer. During monsoon, natural rain is usually sufficient. Ensure container has drainage holes.', order: 3 },
        { title: 'Pollination', icon: '🐝', body: 'Male flowers appear first, female flowers (with a mini fruit at base) come later. If no bees, hand pollinate with a cotton bud.', order: 4 },
        { title: 'Harvesting', icon: '🥒', body: 'Harvest when green, firm and 10–15 cm long (60–70 days from sowing). Leaving fruits on the vine until orange signals the end of that branch\'s productivity.', order: 5 },
      ]},
    },

    // ─── FRUITS ──────────────────────────────────────────────────────────────
    {
      name: 'Dwarf mango', scientificName: 'Mangifera indica', slug: 'dwarf-mango',
      description: 'The king of Indian fruits in a terrace-friendly dwarf variety. Produces real Alphonso-type mangoes in large pots or grow bags.',
      price: 799, comparePrice: 999, stock: 20,
      thumbnailUrl: '/images/plants/mango.jpg', images: ['/images/plants/mango.jpg'],
      categories: ['outdoor', 'fruit'], difficulty: 'intermediate', tags: ['edible', 'dwarf', 'terrace-garden', 'seasonal'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 3 days', careSunlight: 'Full sun (6–8 hrs)', careHumidity: '50–80%', careTemperature: '24–38°C',
      wateringIntervalDays: 3, fertiliserIntervalDays: 30, pruningIntervalDays: 90, repottingIntervalMonths: 24,
      careGuide: { create: [
        { title: 'Pot size', icon: '🪴', body: 'Use a minimum 25-litre grow bag or pot. The bigger the container, the more fruit you get. Re-pot every 2 years.', order: 1 },
        { title: 'Watering', icon: '💧', body: 'Water every 2–3 days in growing season. From November to January reduce watering — this stress triggers flowering.', order: 2 },
        { title: 'Sunlight', icon: '☀️', body: 'Full sun is non-negotiable — 6–8 hours minimum. Terrace is ideal. South or west-facing placement.', order: 3 },
        { title: 'Fertilising', icon: '🧪', body: 'In February–March: apply phosphorus-rich fertiliser to support flowering. In May–June: switch to balanced NPK for fruit development.', order: 4 },
        { title: 'Fruiting season', icon: '🥭', body: 'Dwarf varieties fruit 3–4 years from grafted saplings. Flowers appear in December–February, fruits ripen April–June.', order: 5 },
        { title: 'Pruning', icon: '✂️', body: 'After fruit harvest (July), prune dead or crossing branches. Shape to keep height manageable at 4–5 feet.', order: 6 },
      ]},
    },
    {
      name: 'Guava', scientificName: 'Psidium guajava', slug: 'guava',
      description: 'The most productive fruit tree for Indian home gardens — produces year-round, thrives in containers and is packed with vitamin C.',
      price: 349, comparePrice: 449, stock: 35,
      thumbnailUrl: '/images/plants/guava.jpg', images: ['/images/plants/guava.jpg'],
      categories: ['outdoor', 'fruit'], difficulty: 'beginner', tags: ['edible', 'fast-fruiting', 'vitamin-c', 'terrace-garden'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 3 days', careSunlight: 'Full sun (5–6 hrs)', careHumidity: '40–70%', careTemperature: '20–38°C',
      wateringIntervalDays: 3, fertiliserIntervalDays: 21, pruningIntervalDays: 60,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water every 2–3 days in summer, weekly in winter. Very drought tolerant once established. Avoid waterlogging.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Full sun produces the sweetest fruits. Partial shade is tolerated but reduces yield and sugar content.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Apply NPK 8-8-8 monthly during growing season. Supplementing with vermicompost every 2 months improves fruit size.', order: 3 },
        { title: 'Pruning', icon: '✂️', body: 'Prune after each harvest cycle. Remove dead wood and crossing branches. New side shoots produce the next crop.', order: 4 },
        { title: 'Fruiting', icon: '🍐', body: 'Fruits develop 20–25 weeks after flowering. Pick when skin turns slightly yellow-green and gives to gentle pressure. Taste — it will smell strongly of guava.', order: 5 },
      ]},
    },
    {
      name: 'Lemon (Kagzi Nimbu)', scientificName: 'Citrus limon', slug: 'lemon-kagzi',
      description: 'The most useful fruit tree for Indian kitchens — produces small, aromatic, highly acidic lemons throughout the year in pots.',
      price: 299, comparePrice: 399, stock: 40,
      thumbnailUrl: '/images/plants/lemon.jpg', images: ['/images/plants/lemon.jpg'],
      categories: ['outdoor', 'fruit', 'herb'], difficulty: 'beginner', tags: ['edible', 'year-round', 'pot-friendly', 'kitchen-garden'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 3 days', careSunlight: 'Full sun (5–6 hrs)', careHumidity: '40–60%', careTemperature: '18–38°C',
      wateringIntervalDays: 3, fertiliserIntervalDays: 21, pruningIntervalDays: 60, repottingIntervalMonths: 18,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Keep soil moist but not waterlogged. Water when top 2–3 cm is dry. Overwatering causes yellowing and leaf drop.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'At least 5–6 hours of direct sun. Terrace or balcony with southern exposure works best for heavy fruiting.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Citrus are heavy feeders. Use citrus-specific fertiliser or NPK 15-15-15 monthly. Add iron chelate if leaves turn yellow between veins.', order: 3 },
        { title: 'Pruning', icon: '✂️', body: 'Remove suckers from below the graft. Prune crossing branches after each major fruiting flush to keep tree productive.', order: 4 },
        { title: 'Fruiting', icon: '🍋', body: 'Grafted plants fruit within 1–2 years. Kagzi nimbu is nearly everbearing — you\'ll have fruit 9–10 months of the year!', order: 5 },
      ]},
    },
    {
      name: 'Pomegranate', scientificName: 'Punica granatum', slug: 'pomegranate',
      description: 'Stunning orange-red flowers followed by jewel-like fruit — one of the most drought-tolerant fruit shrubs for Indian gardens.',
      price: 399, comparePrice: 549, stock: 25,
      thumbnailUrl: '/images/plants/pomegranate.jpg', images: ['/images/plants/pomegranate.jpg'],
      categories: ['outdoor', 'fruit', 'flowering'], difficulty: 'beginner', tags: ['edible', 'drought-tolerant', 'antioxidant', 'ornamental'],
      isBestseller: false, isNewArrival: true,
      careWatering: 'Every 4 days', careSunlight: 'Full sun (6–8 hrs)', careHumidity: '30–60%', careTemperature: '18–38°C',
      wateringIntervalDays: 4, fertiliserIntervalDays: 30, pruningIntervalDays: 60,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water deeply but infrequently — every 3–5 days. Pomegranate is drought tolerant. Irregular watering causes fruit splitting.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Loves full sun and heat. Indian summers are perfect. Partial shade reduces fruit quality and quantity.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Feed with balanced fertiliser in February before flowering. Switch to potassium-rich fertiliser when fruits begin to swell.', order: 3 },
        { title: 'Fruiting season', icon: '🪷', body: 'Flowers appear in spring (March–April). Fruits mature 6–7 months later (September–October). Skin turns deep red-pink when ripe.', order: 4 },
        { title: 'Fruit splitting', icon: '⚠️', body: 'Caused by irregular watering or sudden rains after drought. Mulch heavily and maintain consistent moisture during monsoon.', order: 5 },
      ]},
    },
    {
      name: 'Banana (Dwarf Cavendish)', scientificName: 'Musa acuminata', slug: 'banana-dwarf-cavendish',
      description: 'A tropical statement plant that actually produces real bananas — dramatic large leaves, fast growth, perfect for Indian terraces.',
      price: 449, comparePrice: 599, stock: 20,
      thumbnailUrl: '/images/plants/banana.jpg', images: ['/images/plants/banana.jpg'],
      categories: ['outdoor', 'fruit', 'tropical'], difficulty: 'intermediate', tags: ['edible', 'tropical', 'fast-growing', 'statement-plant'],
      isBestseller: false, isNewArrival: true,
      careWatering: 'Every 2 days', careSunlight: 'Full sun (6–8 hrs)', careHumidity: '50–80%', careTemperature: '22–35°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 14,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Bananas need lots of water — water every day in summer. Keep soil moist but ensure excellent drainage. They hate waterlogged roots.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Maximum sunlight for fastest growth. South-facing terrace placement produces fruit in 18–24 months.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Heavy feeder — apply compost or banana peel fertiliser monthly. NPK 8-10-12 every 3 weeks during growing season.', order: 3 },
        { title: 'Pups / offshoots', icon: '🌱', body: 'Remove pups (baby plants at base) until the mother plant flowers. After harvest, cut the mother stem and let one pup grow as the next plant.', order: 4 },
        { title: 'Fruiting', icon: '🍌', body: 'Dwarf Cavendish flowers in 18–24 months and produces fruit 3 months after flowering. A bunch contains 6–9 hands (60–100+ bananas!).', order: 5 },
      ]},
    },

    // ─── HERBS & MEDICINAL ────────────────────────────────────────────────────
    {
      name: 'Tulsi (Holy basil)', scientificName: 'Ocimum tenuiflorum', slug: 'tulsi-holy-basil',
      description: 'India\'s most sacred and medicinal plant — worshipped daily, used in kadha, tea and Ayurveda. Easy to grow anywhere.',
      price: 59, comparePrice: 79, stock: 200,
      thumbnailUrl: '/images/plants/tulsi.jpg', images: ['/images/plants/tulsi.jpg'],
      categories: ['outdoor', 'herb'], difficulty: 'beginner', tags: ['medicinal', 'sacred', 'ayurvedic', 'fast-growing', 'edible'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Full to partial sun (4–6 hrs)', careHumidity: '40–70%', careTemperature: '20–38°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 21, pruningIntervalDays: 14,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Keep soil moist but not waterlogged. Water every 1–2 days in summer. Tulsi wilts in extreme drought — water promptly when soil is dry.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Loves sunlight. 4–6 hours minimum. Balcony, window sill or courtyard all work. More sun = more aromatic oils in leaves.', order: 2 },
        { title: 'Pruning', icon: '✂️', body: 'Pinch off flower buds as soon as they appear. This extends leaf production significantly. A pruned tulsi lives 2–3 years; unpruned dies after seeding.', order: 3 },
        { title: 'Harvesting', icon: '🌿', body: 'Harvest leaves in the morning for maximum essential oils. Never remove more than 1/3 of the plant at once. Fresh, dried or as kadha — all work.', order: 4 },
        { title: 'Medicinal use', icon: '💊', body: 'Tulsi kadha (5 leaves + ginger + honey in hot water) boosts immunity. Leaves are expectorant, antiviral and anti-inflammatory.', order: 5 },
      ]},
    },
    {
      name: 'Curry leaf', scientificName: 'Murraya koenigii', slug: 'curry-leaf',
      description: 'The non-negotiable ingredient of South Indian cooking — grow fresh curry leaves at home and never buy dried ones again.',
      price: 129, comparePrice: 169, stock: 90,
      thumbnailUrl: '/images/plants/curry-leaf.jpg', images: ['/images/plants/curry-leaf.jpg'],
      categories: ['outdoor', 'herb'], difficulty: 'beginner', tags: ['edible', 'cooking', 'aromatic', 'south-indian'],
      isBestseller: true, isNewArrival: false,
      careWatering: 'Every 3 days', careSunlight: 'Full to partial sun (4–6 hrs)', careHumidity: '40–70%', careTemperature: '18–38°C',
      wateringIntervalDays: 3, fertiliserIntervalDays: 21, pruningIntervalDays: 21,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water when top inch is dry — every 2–3 days in summer, weekly in winter. Very tolerant to drying out briefly.', order: 1 },
        { title: 'Sunlight', icon: '☀️', body: 'Needs good sunlight to produce aromatic leaves. Indoor plants near bright windows work, but outdoor is better for kitchen use.', order: 2 },
        { title: 'Fertilising', icon: '🧪', body: 'Apply iron-rich fertiliser (add a few rusty nails to water for a week) if leaves yellow. Nitrogen fertiliser promotes lush leaf growth.', order: 3 },
        { title: 'Harvesting', icon: '🍃', body: 'Pick full sprigs from the outside of the plant. Harvest just before use — curry leaves lose aroma rapidly after picking.', order: 4 },
        { title: 'Root suckers', icon: '🌱', body: 'Curry leaf regularly sends up root suckers — small plants around the base. Pot these up as new plants or remove to keep the main plant vigorous.', order: 5 },
      ]},
    },
    {
      name: 'Aloe vera', scientificName: 'Aloe barbadensis miller', slug: 'aloe-vera',
      description: 'The original Indian beauty and first-aid plant — soothes burns, moisturises skin and grows perfectly in any sunny spot with minimal water.',
      price: 149, comparePrice: 199, stock: 100,
      thumbnailUrl: '/images/plants/aloe-vera.jpg', images: ['/images/plants/aloe-vera.jpg'],
      categories: ['succulent', 'herb', 'outdoor'], difficulty: 'beginner', tags: ['medicinal', 'drought-tolerant', 'beauty', 'kitchen-garden'],
      isBestseller: false, isNewArrival: false,
      careWatering: 'Every 14 days', careSunlight: 'Bright to direct (4–6 hrs)', careHumidity: 'Low (20–40%)', careTemperature: '13–35°C',
      wateringIntervalDays: 14, fertiliserIntervalDays: 90, repottingIntervalMonths: 24,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Water deeply but very infrequently. In summer every 2 weeks; in winter once a month. Let soil dry completely between waterings.', order: 1 },
        { title: 'Light', icon: '☀️', body: 'Loves direct sunlight. Window sill or balcony with 4–6 hours sun is perfect. Indoor rooms that are too dark cause thin, pale leaves.', order: 2 },
        { title: 'Gel harvesting', icon: '💆', body: 'Cut the outer, lower leaves at the base. Slice lengthwise. Scoop out clear gel — apply to burns, skin or mix in smoothies. Avoid the yellow latex layer.', order: 3 },
        { title: 'Pups', icon: '🌱', body: 'Aloe regularly produces baby pups around the base. Remove when 10 cm tall and plant separately — free new plants!', order: 4 },
        { title: 'Medicinal use', icon: '💊', body: 'Fresh gel applied to sunburns, cuts, and rashes provides cooling relief. Drinking 30ml of aloe juice daily (inner gel only) aids digestion.', order: 5 },
      ]},
    },
    {
      name: 'Mint (Pudina)', scientificName: 'Mentha spicata', slug: 'mint-pudina',
      description: 'Rapid-spreading, intensely fragrant — perfect for chutneys, chai, raita and mojitos. Grows in even the tiniest pot on a window sill.',
      price: 49, comparePrice: 69, stock: 180,
      thumbnailUrl: '/images/plants/mint.jpg', images: ['/images/plants/mint.jpg'],
      categories: ['herb', 'outdoor'], difficulty: 'beginner', tags: ['edible', 'aromatic', 'fast-growing', 'cooking', 'pot-friendly'],
      isBestseller: false, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Partial to full sun (3–5 hrs)', careHumidity: '50–70%', careTemperature: '15–30°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 21, pruningIntervalDays: 7,
      careGuide: { create: [
        { title: 'Watering', icon: '💧', body: 'Keep soil consistently moist — mint does not like to dry out. In summer, water daily. Perfect plant to grow in partially shaded areas.', order: 1 },
        { title: 'Containment', icon: '🪴', body: 'Grow mint in pots — it spreads aggressively via underground runners and will take over a garden bed. A single pot is enough.', order: 2 },
        { title: 'Harvesting', icon: '🌿', body: 'Harvest the top 1/3 frequently — this encourages bushy growth. Pick before flowering for best flavour. Pinch flower buds as they appear.', order: 3 },
        { title: 'Propagation', icon: '🌱', body: 'Place a sprig in a glass of water. Roots appear in 5–7 days. Mint from your local market can be rooted this way — free plants!', order: 4 },
        { title: 'Uses', icon: '🍵', body: 'Fresh pudina chutney (leaves + coconut + green chilli + lime). Add to chai, lemonade, raita. Dry and powder for use in biryanis.', order: 5 },
      ]},
    },
    {
      name: 'Coriander (Dhania)', scientificName: 'Coriandrum sativum', slug: 'coriander-dhania',
      description: 'The garnish on every Indian dish — grow fresh coriander in kitchen pots and harvest in just 25 days from sowing.',
      price: 39, comparePrice: 59, stock: 200,
      thumbnailUrl: '/images/plants/coriander.jpg', images: ['/images/plants/coriander.jpg'],
      categories: ['herb', 'outdoor'], difficulty: 'beginner', tags: ['edible', 'super-fast', 'cooking', 'window-sill'],
      isBestseller: false, isNewArrival: false,
      careWatering: 'Every 2 days', careSunlight: 'Partial sun (3–5 hrs)', careHumidity: '40–70%', careTemperature: '15–28°C',
      wateringIntervalDays: 2, fertiliserIntervalDays: 21,
      careGuide: { create: [
        { title: 'Sowing', icon: '🌱', body: 'Crush seeds gently to separate (each has 2 seeds). Sow 1 cm deep, densely. Best season: October–February. Avoid summer — bolts rapidly in heat.', order: 1 },
        { title: 'Watering', icon: '💧', body: 'Keep soil moist but not soggy. Use a spray bottle to avoid disturbing seeds. Water every 1–2 days depending on temperature.', order: 2 },
        { title: 'Harvesting', icon: '🌿', body: 'Cut outer leaves when 15–20 cm tall (25–35 days). Inner leaves keep growing. Alternatively, pull the whole plant at 40 days for a bigger harvest.', order: 3 },
        { title: 'Seeds', icon: '🔵', body: 'Let some plants flower and set seed. Dried coriander seeds are the spice "dhania" used in curry powders. Harvest when brown and dry.', order: 4 },
        { title: 'Bolting', icon: '⚠️', body: 'Coriander bolts (goes to seed) quickly in warm weather. Sow fresh seeds every 3 weeks for continuous supply rather than one large planting.', order: 5 },
      ]},
    },
  ]

  for (const plant of plants) {
    await prisma.plant.upsert({
      where: { slug: plant.slug },
      update: { name: plant.name, description: plant.description, price: plant.price, comparePrice: plant.comparePrice, stock: plant.stock, categories: plant.categories as never, isBestseller: plant.isBestseller, isNewArrival: plant.isNewArrival },
      create: plant as never,
    })
  }

  // ─── SUPPLIES ──────────────────────────────────────────────────────────────
  const supplies = [
    { name: 'Terracotta pot 6"', slug: 'terracotta-pot-6', description: 'Classic breathable clay pot with drainage hole — ideal for succulents, herbs and small plants', price: 89, comparePrice: 120, stock: 200, category: 'pots', badges: ['Drainage hole', '6 inch', 'Breathable'], thumbnailUrl: '/images/supplies/terracotta-6.jpg', images: [] },
    { name: 'Terracotta pot 10"', slug: 'terracotta-pot-10', description: 'Large terracotta pot for medium-sized plants and vegetables', price: 169, comparePrice: 220, stock: 120, category: 'pots', badges: ['Drainage hole', '10 inch', 'Breathable'], thumbnailUrl: '/images/supplies/terracotta-10.jpg', images: [] },
    { name: 'Grow bag 15L', slug: 'grow-bag-15l', description: 'Heavy-duty fabric grow bag — perfect for tomatoes, brinjal, dwarf fruit trees', price: 129, comparePrice: 179, stock: 150, category: 'pots', badges: ['15 litre', 'Reusable', 'UV-resistant'], thumbnailUrl: '/images/supplies/grow-bag.jpg', images: [] },
    { name: 'Grow bag 25L', slug: 'grow-bag-25l', description: 'Extra-large grow bag for dwarf mango, guava, pomegranate and banana', price: 199, comparePrice: 269, stock: 100, category: 'pots', badges: ['25 litre', 'Reusable', 'UV-resistant'], thumbnailUrl: '/images/supplies/grow-bag-25.jpg', images: [] },
    { name: 'Premium potting mix 5kg', slug: 'premium-potting-mix-5kg', description: 'Balanced pH, rich in organic matter — suitable for most houseplants and indoor plants', price: 199, comparePrice: 269, stock: 150, category: 'soil', badges: ['5 kg', 'Balanced pH', 'Sterilised'], thumbnailUrl: '/images/supplies/potting-mix.jpg', images: [] },
    { name: 'Vegetable & fruit potting mix 5kg', slug: 'veggie-fruit-potting-mix-5kg', description: 'Specially formulated for edible plants — enriched with bone meal, neem cake and vermicompost', price: 249, comparePrice: 329, stock: 100, category: 'soil', badges: ['5 kg', 'Neem cake', 'Vermicompost', 'Edible-safe'], thumbnailUrl: '/images/supplies/veggie-mix.jpg', images: [] },
    { name: 'Coco peat block 650g', slug: 'coco-peat-block-650g', description: 'Compressed block expands to 8L of growing medium — excellent water retention', price: 79, comparePrice: 109, stock: 300, category: 'soil', badges: ['650g block', 'Expands 8L', 'Eco-friendly'], thumbnailUrl: '/images/supplies/coco-peat.jpg', images: [] },
    { name: 'Vermicompost 2kg', slug: 'vermicompost-2kg', description: 'Pure worm castings — the richest organic fertiliser for all Indian garden plants', price: 149, comparePrice: 199, stock: 200, category: 'fertiliser', badges: ['2 kg', '100% organic', 'All plants'], thumbnailUrl: '/images/supplies/vermicompost.jpg', images: [] },
    { name: 'NPK liquid fertiliser 500ml', slug: 'npk-liquid-fertiliser-500ml', description: 'Balanced 19:19:19 all-purpose liquid formula — for weekly feeding in growing season', price: 159, comparePrice: 219, stock: 120, category: 'fertiliser', badges: ['500 ml', '19-19-19', 'All plants'], thumbnailUrl: '/images/supplies/npk-fertiliser.jpg', images: [] },
    { name: 'Bloom booster 250ml', slug: 'bloom-booster-250ml', description: 'High-phosphorus concentrate for maximum flowering on hibiscus, bougainvillea and roses', price: 199, comparePrice: 269, stock: 80, category: 'fertiliser', badges: ['High-P', 'More blooms', '250 ml'], thumbnailUrl: '/images/supplies/bloom-booster.jpg', images: [] },
    { name: 'Seaweed growth booster 250ml', slug: 'seaweed-booster-250ml', description: 'Natural organic concentrate — promotes root health, stress tolerance and germination', price: 219, comparePrice: 299, stock: 80, category: 'fertiliser', badges: ['Organic', '250 ml', 'Root health'], thumbnailUrl: '/images/supplies/seaweed.jpg', images: [] },
    { name: 'Neem oil 100ml', slug: 'neem-oil-100ml', description: 'Cold-pressed pure neem oil — organic pest and fungal disease control for all plants', price: 129, comparePrice: 169, stock: 150, category: 'fertiliser', badges: ['100% organic', '100 ml', 'Pest control'], thumbnailUrl: '/images/supplies/neem-oil.jpg', images: [] },
    { name: 'Stainless pruning shears', slug: 'stainless-pruning-shears', description: 'Bypass action, spring-loaded, ergonomic grip — for precise pruning of stems up to 1.5 cm', price: 349, comparePrice: 449, stock: 60, category: 'tools', badges: ['Stainless steel', 'Spring-loaded', 'Ergonomic'], thumbnailUrl: '/images/supplies/shears.jpg', images: [] },
    { name: 'Soil moisture meter', slug: 'soil-moisture-meter', description: 'No-battery 3-in-1 probe — measures moisture, pH and light simultaneously', price: 249, comparePrice: 349, stock: 90, category: 'tools', badges: ['No batteries', '3-in-1', 'Instant read'], thumbnailUrl: '/images/supplies/moisture-meter.jpg', images: [] },
    { name: 'Watering can 5L', slug: 'watering-can-5l', description: 'Long-spout indoor watering can with fine rose head — reaches deep into pots without splashing', price: 299, comparePrice: 399, stock: 70, category: 'tools', badges: ['5 litre', 'Long spout', 'Fine rose'], thumbnailUrl: '/images/supplies/watering-can.jpg', images: [] },
    { name: 'Drip irrigation kit', slug: 'drip-irrigation-kit', description: 'Balcony and terrace drip system for up to 20 pots — set and forget watering', price: 799, comparePrice: 999, stock: 40, category: 'tools', badges: ['20 pots', 'Timer-ready', 'Easy install'], thumbnailUrl: '/images/supplies/drip-kit.jpg', images: [] },
  ]

  for (const supply of supplies) {
    await prisma.supply.upsert({
      where: { slug: supply.slug },
      update: { name: supply.name, description: supply.description, price: supply.price, stock: supply.stock },
      create: supply as never,
    })
  }

  console.info('✅ Database seeded with Indian plant varieties!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
